return {
  setup = function(colors)
    hi("Function", { guifg = colors.syntax.color09, gui = "bold,italic" })
    hi("Method", { guifg = colors.syntax.color01, gui = "bold" })
    hi("Type", { guifg = colors.syntax.color00 })
    hi("StorageClass", { guifg = colors.syntax.color00 })
    hi("Float", { guifg = colors.syntax.color01 })
    hi("Number", { guifg = colors.syntax.color06 })
    hi("Boolean", { guifg = colors.syntax.color03, gui = "bold" })
    hi("String", { guifg = colors.syntax.color04 })
    hi("Character", { guifg = colors.syntax.color05 })
    hi("Constant", { guifg = colors.syntax.color00, gui = "bold" })
    hi("Keyword", { guifg = colors.syntax.color16, gui = "bold" })
    hi("Structure", { link = "Keyword" })
    hi("Label", { guifg = colors.syntax.color00 })
    hi("Operator", { guifg = colors.syntax.color02 })
    hi("Exception", { guifg = colors.syntax.color08 })
    hi("PreProc", { guifg = colors.syntax.color00 })
    hi("Include", { guifg = colors.syntax.color02 })
    hi("Macro", { guifg = colors.syntax.color09 })
    hi("Typedef", { guifg = colors.syntax.color09 })
    hi("PreCondit", { guifg = colors.syntax.color10 })
    hi("Define", { guifg = colors.syntax.color09 })
    hi("Special", { guifg = colors.syntax.color00, gui = "bold,italic" })
    hi("SpecialChar", { guifg = colors.syntax.color09 })
    hi("SpecialComment", { guifg = colors.syntax.color11, gui = "bold,italic" })
    hi("Comment", { guifg = colors.syntax.color14, gui = "italic" })
    hi("Tag", { guifg = colors.syntax.color16 })
    hi("Delimiter", { guifg = colors.syntax.color16 })
    hi("Debug", { guifg = colors.syntax.color17 })
    hi("Underlined", { guifg = colors.syntax.color15, gui = "underline" })
    hi("Ignore", { guifg = colors.syntax.color18 })
    hi("Error", { guifg = colors.syntax.color17, gui = "underline,italic" })
    hi("Todo", { guifg = colors.syntax.color10 })
    hi("Conditional", { guifg = colors.syntax.color00 })
    hi("Repeat", { guifg = colors.syntax.color03 })
    hi("Conceal", { guifg = "NONE" })
    hi("Statement", { guifg = colors.syntax.color00 })
    hi("Identifier", { guifg = colors.syntax.color03 })
  end,
}

-- vim:ft=lua
