vim.cmd.colorscheme("fallback")

require("dharmx.core").exclude({
  "neovide.lua",
  -- "autocmd.lua",
  -- "cmd.lua",
})

require("dharmx.plug").exclude({
  "simrat39/symbols-outline.nvim",
  "sheerun/vim-polyglot",
  "andweeb/presence.nvim",
  "nvim-treesitter/nvim-tree-docs",
  "windwp/nvim-ts-autotag",
  "echasnovski/mini.indentscope",
  "kyazdani42/nvim-tree.lua",
  "hrsh7th/cmp-nvim-lua",
  -- "stevearc/overseer.nvim",
  -- "folke/trouble.nvim",
  -- "ckolkey/ts-node-action",
  -- "stevearc/aerial.nvim",
  -- "stevearc/resession.nvim",
  -- "cbochs/grapple.nvim",
  -- "cbochs/portal.nvim",
  -- "ThePrimeagen/harpoon",
  -- "wakatime/vim-wakatime",
  -- "rcarriga/nvim-dap-ui",
  -- "b0o/incline.nvim",
  -- "theHamsta/nvim-dap-virtual-text",
  -- "nvim-telescope/telescope-dap.nvim",
  -- "jayp0521/mason-nvim-dap.nvim",
  -- "mfussenegger/nvim-dap",
  -- "phelipetls/vim-hugo",
  -- "robertbasic/vim-hugo-helper",
  -- "ggandor/flit.nvim",
  -- "tpope/vim-repeat",
  -- "hinell/move.nvim",
  -- "RRethy/nvim-treesitter-textsubjects",
  -- "RRethy/vim-illuminate",
  -- "folke/todo-comments.nvim",
  -- "SmiteshP/nvim-navic",
  -- "vijaymarupudi/nvim-fzf",
  -- "MattesGroeger/vim-bookmarks",
  -- "rcarriga/nvim-notify",
  -- "kshenoy/vim-signature",
  -- "mbbill/undotree",
  -- "b0o/schemastore.nvim",
  -- "kosayoda/nvim-lightbulb",
  -- "rafcamlet/nvim-luapad",
  -- "elkowar/yuck.vim",
  -- "hrsh7th/cmp-nvim-lsp-signature-help",
  -- "hrsh7th/cmp-nvim-lsp-document-symbol",
  -- "hrsh7th/cmp-cmdline",
  -- "tami5/sqlite.lua",
  -- "simrat39/rust-tools.nvim",
  -- "j-hui/fidget.nvim",
  -- "karb94/neoscroll.nvim",
  -- "tom-anders/telescope-vim-bookmarks.nvim",
  -- "mrjones2014/nvim-ts-rainbow",
  -- "nvim-treesitter/nvim-treesitter-textobjects",
  -- "lukas-reineke/virt-column.nvim",
  -- "petertriho/nvim-scrollbar",
  -- "folke/twilight.nvim",
  -- "Pocco81/TrueZen.nvim",
  -- "yamatsum/nvim-cursorline",
  -- "anuvyklack/pretty-fold.nvim",
  -- "gorbit99/codewindow.nvim",
  -- "ThePrimeagen/refactoring.nvim",
  -- "is0n/jaq-nvim",
  -- "sindrets/diffview.nvim",
  -- "lukas-reineke/indent-blankline.nvim",
  -- "kevinhwang91/nvim-hlslens",
  -- "dnlhc/glance.nvim",
  -- "Fymyte/rasi.vim",
  -- "kovetskiy/sxhkd-vim",
  -- "MTDL9/vim-log-highlighting",
  -- "TimUntersberger/neogit",
  -- "lewis6991/gitsigns.nvim",
  -- "goolord/alpha-nvim",
})

-- vim:filetype=lua
