-- This file has been generated by regen.py
-- Changes may be overwritten the next time 
-- configs are re-generated

local N = {}

N.common = {
  ["base00"] = "#101317",
  ["base01"] = "#171C21",
  ["base02"] = "#1c2026",
  ["base03"] = "#20252b",

  ["base04"] = "#949494",
  ["base05"] = "#d4d4d5",
  ["base06"] = "#ffffff",

  ["base07"] = "#54ced6",
  ["base08"] = "#70c0ba",
  ["base09"] = "#7ab0df",
  ["base10"] = "#b77ee0",

  ["base11"] = "#f87070",
  ["base12"] = "#36c692",
  ["base13"] = "#ffe59e",
  ["base14"] = "#79dcaa",
  ["base15"] = "#c397d8",
}

N.shades = {
  ["shade00"] = "#3d464e",
  ["shade01"] = "#2b3238",
  ["shade02"] = "#24292e",
  ["shade03"] = "#1f2429",
  ["shade04"] = "#1c2126",
  ["shade05"] = "#191e23",
  ["shade06"] = "#161b20",
  ["shade07"] = "#151a1f",
  ["shade08"] = "#13181d",
  ["shade09"] = "#11161b",
  ["shade10"] = "#0e1115",
  ["shade11"] = "#0c0f13",
  ["shade12"] = "#0a0d11",
}

N.rainbow = {
  ["cobalt"] = "#7ab0df",
  ["pink"] = "#b77ee0",
  ["cyan"] = "#54ced6",
  ["green"] = "#79dcaa",
  ["yellow"] = "#ffe59e",
  ["orange"] = "#f87070",
  ["purple"] = "#c397d8",
}

N.modes = setmetatable({
  ["n"] = "#79dcaa",
  ["no"] = "#70c0ba",
  ["v"] = "#7ab0df",
  ["V"] = "#63b3ad",
  [""] = "#f87070",
  ["s"] = "#c397d8",
  ["S"] = "#b77ee0",
  [""] = "#f87070 ",
  ["i"] = "#54ced6",
  ["ic"] = "#54ced6",
  ["R"] = "#e5d487",
  ["Rv"] = "#ffe59e",
  ["c"] = "#c397d8",
  ["cv"] = "#36c692",
  ["ce"] = "#36c692",
  ["r"] = "#54ced6",
  ["rm"] = "#70c0ba",
  ["r?"] = "#37d99e",
  ["t"] = "#F186b5",
}, {
  __index = function()
    return "#F186b5"
  end,
})

N.syntax = {
  ["color16"] = "#7ab0df",
  ["color09"] = "#c397d8",

  ["color00"] = "#f87070",
  ["color03"] = "#b77ee0",
  ["color02"] = "#36c692",
  ["color19"] = "#54ced6",

  ["color17"] = "#70c0ba",
  ["color20"] = "#5fb0fc",

  ["color13"] = "#e87979",
  ["color01"] = "#e25656",
  ["color05"] = "#63b3ad",

  ["color12"] = "#79dcaa",
  ["color15"] = "#79dcaa",
  ["color04"] = "#37d99e",

  ["color06"] = "#F186b5",
  ["color08"] = "#e5d487",

  ["color10"] = "#ffe59e",
  ["color11"] = "#ffe59e",

  ["color18"] = "#949494",
  ["color14"] = "#828282",
  ["color07"] = "#d4d4d5",
}

return N

-- vim:ft=lua
