return {
  setup = function(colors)
    hi("MatchParen", { guifg = colors.common.base08, gui = "bold" })
    hi("Normal", { guibg = colors.common.base00 })
    hi("NormalFloat", { guifg = colors.common.base08, guibg = colors.shades.shade08, blend = 2 })
    hi("cheatSeparator", { guifg = colors.common.base02 })
    hi("FloatBorder", { guifg = colors.shades.shade08, guibg = colors.shades.shade08, blend = 2 })
    hi("ColorColumn", { guibg = colors.common.base01 })
    hi("Conceal", { guifg = colors.common.base01 })
    hi("Directory", { guifg = colors.common.base07 })
    hi("DiffAdd", { guifg = colors.common.base14, gui = "reverse" })
    hi("DiffChange", { guifg = colors.common.base13, gui = "reverse" })
    hi("DiffDelete", { guifg = colors.common.base11, gui = "reverse" })
    hi("DiffText", { guifg = colors.common.base15, gui = "reverse" })
    hi("EndOfBuffer", { guifg = colors.common.base01 })
    hi("ErrorMsg", { guifg = colors.common.base11, gui = "undercurl,italic" })
    hi("Folded", { guifg = colors.common.base03, gui = "italic" })
    hi("FoldColumn", { guifg = colors.common.base07 })
    hi("IncSearch", { guifg = colors.common.base13, guibg = colors.common.base02 })
    hi("LineNr", { guifg = colors.shades.shade01, gui = "bold" })
    hi("LineNrAbove", { guifg = colors.common.base13, gui = "bold" })
    hi("LineNrBelow", { guifg = colors.common.base15, gui = "bold" })
    hi("SignColumn", { link = "Normal" })
    hi("VertSplit", { guifg = colors.shades.shade03 })
    hi("WinSeparator", { guifg = colors.shades.shade03 })
    hi("CursorLineNr", { guifg = colors.common.base08, gui = "bold" })
    hi("CursorLine", { guibg = "NONE" })
    hi("ModeMsg", { guifg = colors.common.base14, gui = "bold" })
    hi("MsgArea", { guifg = colors.common.base09, gui = "bold" })
    hi("MsgSeparator", { guifg = colors.common.base15, gui = "bold" })
    hi("MoreMsg", { guifg = colors.common.base09 })
    hi("NonText", { guifg = colors.shades.shade03 })
    hi("PmenuSel", { guibg = colors.common.base03, guifg = colors.common.base14, gui = "bold", blend = 2 })
    hi("PmenuSbar", { guibg = colors.shades.shade04, blend = 2 })
    hi("PmenuThumb", { guibg = colors.common.base03, blend = 2 })
    hi("Question", { guifg = colors.common.base14 })
    hi("QuickFixLine", { guifg = colors.common.base04, gui = "reverse" })
    hi("qfLineNr", { guifg = colors.common.base04, gui = "reverse" })
    hi("Search", { guifg = colors.common.base10, guibg = colors.common.base06, gui = "reverse" })
    hi("SpecialKey", { guifg = colors.common.base09 })
    hi("SpellBad", { guifg = colors.common.base11, gui = "undercurl,italic" })
    hi("SpellCap", { guifg = colors.common.base07, gui = "undercurl,italic" })
    hi("SpellLocal", { guifg = colors.common.base08, gui = "italic" })
    hi("SpellRare", { guifg = colors.common.base09, gui = "italic" })
    hi("TabLineFill", { guifg = colors.common.base04 })
    hi("TablineSel", { guifg = colors.common.base01, guibg = colors.common.base09 })
    hi("Tabline", { guifg = colors.common.base04, guibg = colors.common.base01 })
    hi("Title", { guifg = colors.common.base14, gui = "bold" })
    hi("Visual", { guibg = colors.shades.shade05 })
    hi("VisualNC", { guibg = colors.common.base11, guifg = colors.common.base13 })
    hi("VisualNOS", { guibg = colors.shades.shade05, guifg = colors.common.base13 })
    hi("WarningMsg", { guifg = colors.common.base15, gui = "underline,italic" })
    hi("WildMenu", { guifg = colors.common.base12, gui = "bold" })
    hi("CursorColumn", { guibg = colors.common.base01 })
    hi("ToolbarLine", { guifg = colors.common.base04, guibg = colors.common.base01 })
    hi("ToolbarButton", { guifg = colors.common.base04, gui = "bold" })
    hi("NormalMode", { guifg = colors.common.base04, gui = "reverse" })
    hi("InsertMode", { guifg = colors.common.base14, gui = "reverse" })
    hi("ReplacelMode", { guifg = colors.common.base11, gui = "reverse" })
    hi("VisualMode", { guifg = colors.common.base09, gui = "reverse" })
    hi("CommandMode", { guifg = colors.common.base04, gui = "reverse" })
    hi("Warnings", { guifg = colors.common.base15 })
    hi("healthError", { guifg = colors.common.base11 })
    hi("healthSuccess", { guifg = colors.common.base14 })
    hi("healthWarning", { guifg = colors.common.base15 })
  end,
}

-- vim:ft=lua
