local function HL(name, val) vim.api.nvim_set_hl(0, name, val) end

vim.g.colors_name = "radium_dark"
vim.o.background = "dark"

HL("@boolean", { bold = true, foreground = "#F87070" })
HL("@character", { foreground = "#E1C58D" })
HL("@comment", { foreground = "#515C68" })
HL("@conditional", { foreground = "#F87070" })
HL("@constant", { bold = true, foreground = "#FF6666" })
HL("@constant.builtin", { bold = true, foreground = "#FFDF85" })
HL("@constant.macro", { foreground = "#E37070" })
HL("@constructor", { foreground = "#5FB0FC" })
HL("@debug", { foreground = "#7AAFC5" })
HL("@define", { foreground = "#C397D8" })
HL("@exception", { foreground = "#36C692" })
HL("@field", { foreground = "#36C692" })
HL("@float", { foreground = "#F3A4F1" })
HL("@function", { foreground = "#BE8FD7" })
HL("@function.builtin", { bold = true, foreground = "#36C692" })
HL("@function.macro", { foreground = "#FF7070" })
HL("@include", { bold = true, foreground = "#6AA6DF" })
HL("@keyword", { foreground = "#66B3FF" })
HL("@keyword.function", { foreground = "#FB7373" })
HL("@keyword.operator", { foreground = "#70C0BA" })
HL("@keyword.return", { foreground = "#66B3FF" })
HL("@label", { foreground = "#F87070" })
HL("@macro", { foreground = "#F98989" })
HL("@method", { foreground = "#B77EE0" })
HL("@namespace", { foreground = "#60B0FC" })
HL("@number", { foreground = "#54CED6" })
HL("@operator", { foreground = "#70C0BA" })
HL("@parameter", { foreground = "#FFE49D" })
HL("@preproc", { foreground = "#F96262" })
HL("@property", { foreground = "#54CED6" })
HL("@punctuation", { foreground = "#7AB0DF" })
HL("@punctuation.bracket", { foreground = "#FF7D7D" })
HL("@punctuation.delimiter", { foreground = "#7AB0DF" })
HL("@repeat", { foreground = "#B77EE0" })
HL("@storageclass", { foreground = "#F75858" })
HL("@string", { foreground = "#79DCAA" })
HL("@string.escape", { foreground = "#E5E49D" })
HL("@string.regex", { foreground = "#FFE390" })
HL("@string.special", { foreground = "#FCCF67" })
HL("@structure", { foreground = "#5FB0FC" })
HL("@tag", { foreground = "#7AB0DF" })
HL("@text", { foreground = "#D4D4D5" })
HL("@text.literal", { foreground = "#79CFAA" })
HL("@text.reference", { foreground = "#7AB0DF" })
HL("@text.title", { bold = true, foreground = "#FA6969" })
HL("@text.todo", { foreground = "#FFE59E" })
HL("@text.underline", { underline = true })
HL("@text.uri", { foreground = "#FB7373", underline = true })
HL("@type", { foreground = "#F87070" })
HL("@type.definition", { foreground = "#C397D8" })
HL("@variable", { foreground = "#D4D4D5" })
HL("AlphaButtonLabelText", { foreground = "#FFE59E" })
HL("AlphaFooting", { bold = true, foreground = "#C397D8" })
HL("AlphaHeading", { foreground = "#1A1F25" })
HL("AlphaKeyPrefix", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("AlphaLoaded", { foreground = "#24292F" })
HL("AlphaScroll", { foreground = "#C397D8" })
HL("Bold", { bold = true })
HL("BookmarkAnnotationLine", { foreground = "#DDB1F2" })
HL("BookmarkAnnotationSign", { foreground = "#C397D8" })
HL("BookmarkLine", { background = "#FF8A8A" })
HL("BookmarkSign", { foreground = "#F87070" })
HL("Boolean", { bold = true, foreground = "#F87070" })
HL("BufferLineBackground", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineBuffer", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineBufferSelected", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("BufferLineBufferVisible", { background = "#14171E", foreground = "#7AB0DF" })
HL("BufferLineCloseButton", { background = "#14171E", foreground = "#F87070" })
HL("BufferLineCloseButtonVisible", { background = "#14171E", foreground = "#F87070" })
HL("BufferLineDiagnostic", { background = "#0C0E11", foreground = "#3C454E" })
HL("BufferLineDiagnosticSelected", { background = "#101317", bold = true, foreground = "#9F9F9F", italic = true })
HL("BufferLineDiagnosticVisible", { background = "#0E1115", foreground = "#3C454E" })
HL("BufferLineDuplicate", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineDuplicateSelected", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineDuplicateVisible", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineError", { background = "#0C0E11", foreground = "#515C68", special = "#F87070" })
HL("BufferLineErrorDiagnostic", { background = "#0C0E11", foreground = "#3C454E", special = "#BA5454" })
HL(
  "BufferLineErrorDiagnosticSelected",
  { background = "#101317", bold = true, foreground = "#BA5454", italic = true, special = "#BA5454" }
)
HL("BufferLineErrorDiagnosticVisible", { background = "#0E1115", foreground = "#3C454E" })
HL(
  "BufferLineErrorSelected",
  { background = "#101317", bold = true, foreground = "#F87070", italic = true, special = "#F87070" }
)
HL("BufferLineErrorVisible", { background = "#0E1115", foreground = "#515C68" })
HL("BufferLineFill", { background = "#101317", foreground = "#313743" })
HL("BufferLineGroupLabel", { background = "#515C68", foreground = "#080A0C" })
HL("BufferLineGroupSeparator", { background = "#080A0C", foreground = "#515C68" })
HL("BufferLineHint", { background = "#0C0E11", foreground = "#515C68", special = "#C397D8" })
HL("BufferLineHintDiagnostic", { background = "#0C0E11", foreground = "#3C454E", special = "#9271A2" })
HL(
  "BufferLineHintDiagnosticSelected",
  { background = "#101317", bold = true, foreground = "#9271A2", italic = true, special = "#9271A2" }
)
HL("BufferLineHintDiagnosticVisible", { background = "#0E1115", foreground = "#3C454E" })
HL(
  "BufferLineHintSelected",
  { background = "#101317", bold = true, foreground = "#C397D8", italic = true, special = "#C397D8" }
)
HL("BufferLineHintVisible", { background = "#0E1115", foreground = "#515C68" })
HL("BufferLineIndicatorSelected", { background = "#7AB0DF", foreground = "#7AB0DF" })
HL("BufferLineIndicatorVisible", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineInfo", { background = "#0C0E11", foreground = "#515C68", special = "#7AB0DF" })
HL("BufferLineInfoDiagnostic", { background = "#0C0E11", foreground = "#3C454E", special = "#5B84A7" })
HL(
  "BufferLineInfoDiagnosticSelected",
  { background = "#101317", bold = true, foreground = "#5B84A7", italic = true, special = "#5B84A7" }
)
HL("BufferLineInfoDiagnosticVisible", { background = "#0E1115", foreground = "#3C454E" })
HL(
  "BufferLineInfoSelected",
  { background = "#101317", bold = true, foreground = "#7AB0DF", italic = true, special = "#7AB0DF" }
)
HL("BufferLineInfoVisible", { background = "#0E1115", foreground = "#515C68" })
HL("BufferLineModified", { background = "#14171E", foreground = "#79DCAA" })
HL("BufferLineModifiedSelected", { background = "#7AB0DF", foreground = "#101317" })
HL("BufferLineModifiedVisible", { background = "#14171E", foreground = "#79DCAA" })
HL("BufferLineNumbers", { background = "#0C0E11", foreground = "#515C68" })
HL("BufferLineNumbersSelected", { background = "#101317", bold = true, foreground = "#D4D4D5", italic = true })
HL("BufferLineNumbersVisible", { background = "#0E1115", foreground = "#515C68" })
HL("BufferLineOffsetSeparator", { background = "#7AB0DF", foreground = "#7AB0DF" })
HL("BufferLinePick", { background = "#14171E", bold = true, foreground = "#D997C8" })
HL("BufferLinePickSelected", { background = "#7AB0DF", bold = true, foreground = "#E6CFA1" })
HL("BufferLinePickVisible", { background = "#14171E", bold = true, foreground = "#FCCF67" })
HL("BufferLineSeparator", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineSeparatorSelected", { background = "#7AB0DF", foreground = "#7AB0DF" })
HL("BufferLineSeparatorVisible", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineTab", { background = "#14171E", foreground = "#242A36" })
HL("BufferLineTabClose", { background = "#101317", foreground = "#F87070" })
HL("BufferLineTabSelected", { background = "#101317", bold = true, foreground = "#7AB0DF" })
HL("BufferLineTabSeparator", { background = "#14171E", foreground = "#14171E" })
HL("BufferLineTabSeparatorSelected", { foreground = "#101317" })
HL("BufferLineWarning", { background = "#0C0E11", foreground = "#515C68", special = "#F97F7F" })
HL("BufferLineWarningDiagnostic", { background = "#0C0E11", foreground = "#3C454E", special = "#BA5F5F" })
HL(
  "BufferLineWarningDiagnosticSelected",
  { background = "#101317", bold = true, foreground = "#BA5F5F", italic = true, special = "#BA5F5F" }
)
HL("BufferLineWarningDiagnosticVisible", { background = "#0E1115", foreground = "#3C454E" })
HL(
  "BufferLineWarningSelected",
  { background = "#101317", bold = true, foreground = "#F97F7F", italic = true, special = "#F97F7F" }
)
HL("BufferLineWarningVisible", { background = "#0E1115", foreground = "#515C68" })
HL("BufferLinecloseButtonSelected", { background = "#7AB0DF", foreground = "#101317" })
HL("Character", { foreground = "#E1C58D" })
HL("CmpItemAbbr", { foreground = "#BABABE" })
HL("CmpItemAbbrDeprecated", { foreground = "#3E4450" })
HL("CmpItemAbbrDeprecatedDefault", { foreground = "#80A0FF" })
HL("CmpItemAbbrMatch", { foreground = "#79DCAA" })
HL("CmpItemAbbrMatchFuzzy", { foreground = "#FCCF67" })
HL("CmpItemKind", { foreground = "#3E4450" })
HL("CmpItemKindClass", { foreground = "#F87070" })
HL("CmpItemKindClassDefault", { foreground = "#3E4450" })
HL("CmpItemKindColor", { foreground = "#7AB0DF" })
HL("CmpItemKindColorDefault", { foreground = "#3E4450" })
HL("CmpItemKindConstant", { foreground = "#FF6666" })
HL("CmpItemKindConstantDefault", { foreground = "#3E4450" })
HL("CmpItemKindConstructorDefault", { foreground = "#3E4450" })
HL("CmpItemKindDefault", { foreground = "#FFA500" })
HL("CmpItemKindEnum", { foreground = "#54CED6" })
HL("CmpItemKindEnumDefault", { foreground = "#3E4450" })
HL("CmpItemKindEnumMember", { foreground = "#C297B9" })
HL("CmpItemKindEnumMemberDefault", { foreground = "#3E4450" })
HL("CmpItemKindEvent", { foreground = "#7AAFF3" })
HL("CmpItemKindEventDefault", { foreground = "#3E4450" })
HL("CmpItemKindField", { foreground = "#FFE69F" })
HL("CmpItemKindFieldDefault", { foreground = "#3E4450" })
HL("CmpItemKindFile", { foreground = "#FCCF67" })
HL("CmpItemKindFileDefault", { foreground = "#3E4450" })
HL("CmpItemKindFolder", { foreground = "#FCCF67" })
HL("CmpItemKindFolderDefault", { foreground = "#3E4450" })
HL("CmpItemKindFunction", { foreground = "#BE8FD7" })
HL("CmpItemKindFunctionDefault", { foreground = "#3E4450" })
HL("CmpItemKindInterface", { foreground = "#C397D8" })
HL("CmpItemKindInterfaceDefault", { foreground = "#3E4450" })
HL("CmpItemKindKeyword", { foreground = "#66B3FF" })
HL("CmpItemKindKeywordDefault", { foreground = "#3E4450" })
HL("CmpItemKindMethod", { foreground = "#DC7272" })
HL("CmpItemKindMethodDefault", { foreground = "#3E4450" })
HL("CmpItemKindModule", { foreground = "#5FB0FC" })
HL("CmpItemKindModuleDefault", { foreground = "#3E4450" })
HL("CmpItemKindOperator", { foreground = "#70C0BA" })
HL("CmpItemKindOperatorDefault", { foreground = "#3E4450" })
HL("CmpItemKindPropertyDefault", { foreground = "#3E4450" })
HL("CmpItemKindReference", { foreground = "#FB7373" })
HL("CmpItemKindReferenceDefault", { foreground = "#3E4450" })
HL("CmpItemKindSnippet", { foreground = "#FFE59E" })
HL("CmpItemKindSnippetDefault", { foreground = "#3E4450" })
HL("CmpItemKindStruct", { foreground = "#5FB0FC" })
HL("CmpItemKindStructDefault", { foreground = "#3E4450" })
HL("CmpItemKindText", { foreground = "#5FB0FC" })
HL("CmpItemKindTextDefault", { foreground = "#3E4450" })
HL("CmpItemKindTypeParameterDefault", { foreground = "#3E4450" })
HL("CmpItemKindUnit", { foreground = "#54CED6" })
HL("CmpItemKindUnitDefault", { foreground = "#3E4450" })
HL("CmpItemKindValue", { foreground = "#79DCAA" })
HL("CmpItemKindValueDefault", { foreground = "#3E4450" })
HL("CmpItemKindVariable", { foreground = "#36C692" })
HL("CmpItemKindVariableDefault", { foreground = "#3E4450" })
HL("CmpItemMenu", { foreground = "#7AB0DF" })
HL("ColorColumn", { background = "#111419", foreground = "#171A20" })
HL("Comment", { foreground = "#515C68" })
HL("Conceal", { foreground = "#1C2228" })
HL("Conditional", { foreground = "#F87070" })
HL("Constant", { foreground = "#FF6666" })
HL("Cursor", { background = "#DFC184", foreground = "#101317" })
HL("CursorColumn", { background = "#191D21" })
HL("CursorLine", { background = "#191D21" })
HL("CursorLineFold", { background = "#101317", foreground = "#70C0BA" })
HL("CursorLineNr", { bold = true, foreground = "#FFE59E" })
HL("CursorLineSign", { background = "#101317" })
HL("Debug", { foreground = "#FB7373" })
HL("Decorator", { foreground = "#FFE59E" })
HL("Define", { foreground = "#C397D8" })
HL("Delimeter", { foreground = "#7AB0DF" })
HL("Delimiter", { foreground = "#FB7373" })
HL("DevIconAi", { foreground = "#CBCB41" })
HL("DevIconAwk", { foreground = "#4D5A5E" })
HL("DevIconBabelrc", { foreground = "#CBCB41" })
HL("DevIconBash", { foreground = "#89E051" })
HL("DevIconBashProfile", { foreground = "#89E051" })
HL("DevIconBashrc", { foreground = "#89E051" })
HL("DevIconBat", { foreground = "#C1F12E" })
HL("DevIconBinaryGLTF", { foreground = "#FFB13B" })
HL("DevIconBmp", { foreground = "#A074C4" })
HL("DevIconBrewfile", { foreground = "#701516" })
HL("DevIconC", { foreground = "#7AB0DF" })
HL("DevIconCMake", { foreground = "#6D8086" })
HL("DevIconCMakeLists", { foreground = "#6D8086" })
HL("DevIconCPlusPlus", { foreground = "#F34B7D" })
HL("DevIconCSS", { foreground = "#5FB0FC" })
HL("DevIconClojure", { foreground = "#8DC149" })
HL("DevIconClojureC", { foreground = "#8DC149" })
HL("DevIconClojureDart", { foreground = "#519ABA" })
HL("DevIconClojureJS", { foreground = "#519ABA" })
HL("DevIconCobol", { foreground = "#005CA5" })
HL("DevIconCoffee", { foreground = "#CBCB41" })
HL("DevIconConf", { foreground = "#6D8086" })
HL("DevIconConfigRu", { foreground = "#701516" })
HL("DevIconConfiguration", { foreground = "#ECECEC" })
HL("DevIconCp", { foreground = "#519ABA" })
HL("DevIconCpp", { foreground = "#519ABA" })
HL("DevIconCrystal", { foreground = "#000000" })
HL("DevIconCs", { foreground = "#596706" })
HL("DevIconCsh", { foreground = "#4D5A5E" })
HL("DevIconCson", { foreground = "#CBCB41" })
HL("DevIconCsv", { foreground = "#89E051" })
HL("DevIconCxx", { foreground = "#519ABA" })
HL("DevIconD", { foreground = "#427819" })
HL("DevIconDart", { foreground = "#03589C" })
HL("DevIconDb", { foreground = "#DAD8D8" })
HL("DevIconDeb", { foreground = "#F76767" })
HL("DevIconDefault", { foreground = "#C7C7CA" })
HL("DevIconDesktopEntry", { foreground = "#563D7C" })
HL("DevIconDiff", { foreground = "#41535B" })
HL("DevIconDoc", { foreground = "#185ABD" })
HL("DevIconDockerfile", { foreground = "#384D54" })
HL("DevIconDrools", { foreground = "#FFAFAF" })
HL("DevIconDropbox", { foreground = "#0061FE" })
HL("DevIconDsStore", { foreground = "#41535B" })
HL("DevIconDump", { foreground = "#DAD8D8" })
HL("DevIconEdn", { foreground = "#519ABA" })
HL("DevIconEex", { foreground = "#A074C4" })
HL("DevIconEjs", { foreground = "#CBCB41" })
HL("DevIconElm", { foreground = "#519ABA" })
HL("DevIconEnv", { foreground = "#FAF743" })
HL("DevIconEpp", { foreground = "#FFA61A" })
HL("DevIconErb", { foreground = "#701516" })
HL("DevIconErl", { foreground = "#B83998" })
HL("DevIconEx", { foreground = "#A074C4" })
HL("DevIconExs", { foreground = "#A074C4" })
HL("DevIconFavicon", { foreground = "#CBCB41" })
HL("DevIconFennel", { foreground = "#FFF3D7" })
HL("DevIconFish", { foreground = "#4D5A5E" })
HL("DevIconFs", { foreground = "#519ABA" })
HL("DevIconFsharp", { foreground = "#519ABA" })
HL("DevIconFsi", { foreground = "#519ABA" })
HL("DevIconFsscript", { foreground = "#519ABA" })
HL("DevIconFsx", { foreground = "#519ABA" })
HL("DevIconGDScript", { foreground = "#6D8086" })
HL("DevIconGemfile", { foreground = "#701516" })
HL("DevIconGemspec", { foreground = "#701516" })
HL("DevIconGif", { foreground = "#A074C4" })
HL("DevIconGitAttributes", { foreground = "#41535B" })
HL("DevIconGitCommit", { foreground = "#41535B" })
HL("DevIconGitConfig", { foreground = "#41535B" })
HL("DevIconGitIgnore", { foreground = "#41535B" })
HL("DevIconGitLogo", { foreground = "#F14C28" })
HL("DevIconGitModules", { foreground = "#41535B" })
HL("DevIconGitlabCI", { foreground = "#E24329" })
HL("DevIconGo", { foreground = "#519ABA" })
HL("DevIconGodotProject", { foreground = "#6D8086" })
HL("DevIconGraphQL", { foreground = "#E535AB" })
HL("DevIconGruntfile", { foreground = "#E37933" })
HL("DevIconGulpfile", { foreground = "#CC3E44" })
HL("DevIconGvimrc", { foreground = "#019833" })
HL("DevIconH", { foreground = "#A074C4" })
HL("DevIconHTML", { foreground = "#F87070" })
HL("DevIconHaml", { foreground = "#EAEAE1" })
HL("DevIconHbs", { foreground = "#F0772B" })
HL("DevIconHeex", { foreground = "#A074C4" })
HL("DevIconHh", { foreground = "#A074C4" })
HL("DevIconHpp", { foreground = "#A074C4" })
HL("DevIconHrl", { foreground = "#B83998" })
HL("DevIconHs", { foreground = "#A074C4" })
HL("DevIconHtm", { foreground = "#E34C26" })
HL("DevIconHxx", { foreground = "#A074C4" })
HL("DevIconIco", { foreground = "#CBCB41" })
HL("DevIconImportConfiguration", { foreground = "#ECECEC" })
HL("DevIconIni", { foreground = "#6D8086" })
HL("DevIconJPEG", { foreground = "#C397D8" })
HL("DevIconJPG", { foreground = "#C397D8" })
HL("DevIconJS", { foreground = "#FFE59E" })
HL("DevIconJava", { foreground = "#CC3E44" })
HL("DevIconJl", { foreground = "#A270BA" })
HL("DevIconJson", { foreground = "#CBCB41" })
HL("DevIconJson5", { foreground = "#CBCB41" })
HL("DevIconJsx", { foreground = "#519ABA" })
HL("DevIconKotlinScript", { foreground = "#7F52FF" })
HL("DevIconKsh", { foreground = "#4D5A5E" })
HL("DevIconKt", { foreground = "#FE7676" })
HL("DevIconLeex", { foreground = "#A074C4" })
HL("DevIconLess", { foreground = "#563D7C" })
HL("DevIconLhs", { foreground = "#A074C4" })
HL("DevIconLicense", { foreground = "#CBCB41" })
HL("DevIconLock", { foreground = "#1D2024" })
HL("DevIconLog", { foreground = "#FFFFFF" })
HL("DevIconLua", { foreground = "#7AB0DF" })
HL("DevIconLuau", { foreground = "#51A0CF" })
HL("DevIconMP3", { foreground = "#FCCF67" })
HL("DevIconMP4", { foreground = "#FFE59E" })
HL("DevIconMakefile", { foreground = "#6D8086" })
HL("DevIconMarkdown", { foreground = "#519ABA" })
HL("DevIconMaterial", { foreground = "#B83998" })
HL("DevIconMd", { foreground = "#FFFFFF" })
HL("DevIconMdx", { foreground = "#519ABA" })
HL("DevIconMint", { foreground = "#87C095" })
HL("DevIconMixLock", { foreground = "#A074C4" })
HL("DevIconMjs", { foreground = "#F1E05A" })
HL("DevIconMl", { foreground = "#E37933" })
HL("DevIconMli", { foreground = "#E37933" })
HL("DevIconMotoko", { foreground = "#9772FB" })
HL("DevIconMustache", { foreground = "#E37933" })
HL("DevIconNPMIgnore", { foreground = "#E8274B" })
HL("DevIconNPMrc", { foreground = "#E8274B" })
HL("DevIconNim", { foreground = "#F3D400" })
HL("DevIconNix", { foreground = "#7EBAE4" })
HL("DevIconNodeModules", { foreground = "#E8274B" })
HL("DevIconOPUS", { foreground = "#F88A02" })
HL("DevIconOpenTypeFont", { foreground = "#ECECEC" })
HL("DevIconOut", { foreground = "#79DCAA" })
HL("DevIconPNG", { foreground = "#C397D8" })
HL("DevIconPackageJson", { foreground = "#E8274B" })
HL("DevIconPackageLockJson", { foreground = "#7A0D21" })
HL("DevIconPackedResource", { foreground = "#6D8086" })
HL("DevIconPdf", { foreground = "#B30B00" })
HL("DevIconPhp", { foreground = "#A074C4" })
HL("DevIconPl", { foreground = "#519ABA" })
HL("DevIconPm", { foreground = "#519ABA" })
HL("DevIconPp", { foreground = "#FFA61A" })
HL("DevIconPpt", { foreground = "#CB4A32" })
HL("DevIconPrisma", { foreground = "#FFFFFF" })
HL("DevIconProcfile", { foreground = "#A074C4" })
HL("DevIconProlog", { foreground = "#E4B854" })
HL("DevIconPromptPs1", { foreground = "#4D5A5E" })
HL("DevIconPsb", { foreground = "#519ABA" })
HL("DevIconPsd", { foreground = "#519ABA" })
HL("DevIconPyc", { foreground = "#FFE291" })
HL("DevIconPyd", { foreground = "#FFE291" })
HL("DevIconPyo", { foreground = "#FFE291" })
HL("DevIconPython", { foreground = "#FFE59E" })
HL("DevIconQuery", { foreground = "#90A850" })
HL("DevIconR", { foreground = "#358A5B" })
HL("DevIconRPM", { foreground = "#FF7063" })
HL("DevIconRake", { foreground = "#701516" })
HL("DevIconRakefile", { foreground = "#701516" })
HL("DevIconRb", { foreground = "#FC6D6D" })
HL("DevIconRlib", { foreground = "#DEA584" })
HL("DevIconRmd", { foreground = "#519ABA" })
HL("DevIconRproj", { foreground = "#358A5B" })
HL("DevIconRs", { foreground = "#DEA584" })
HL("DevIconRss", { foreground = "#FB9D3B" })
HL("DevIconSass", { foreground = "#F55385" })
HL("DevIconScala", { foreground = "#CC3E44" })
HL("DevIconScheme", { foreground = "#000000" })
HL("DevIconScss", { foreground = "#F55385" })
HL("DevIconSettingsJson", { foreground = "#854CC7" })
HL("DevIconSh", { foreground = "#4D5A5E" })
HL("DevIconSig", { foreground = "#E37933" })
HL("DevIconSlim", { foreground = "#E34C26" })
HL("DevIconSln", { foreground = "#854CC7" })
HL("DevIconSml", { foreground = "#E37933" })
HL("DevIconSolidity", { foreground = "#519ABA" })
HL("DevIconSql", { foreground = "#DAD8D8" })
HL("DevIconStyl", { foreground = "#8DC149" })
HL("DevIconSuo", { foreground = "#854CC7" })
HL("DevIconSvelte", { foreground = "#FF3E00" })
HL("DevIconSvg", { foreground = "#FFB13B" })
HL("DevIconSwift", { foreground = "#E37933" })
HL("DevIconSystemVerilog", { foreground = "#019833" })
HL("DevIconTFVars", { foreground = "#5F43E9" })
HL("DevIconTOML", { foreground = "#929299" })
HL("DevIconTS", { foreground = "#5FB0FC" })
HL("DevIconTcl", { foreground = "#1E5CB3" })
HL("DevIconTerminal", { foreground = "#31B53E" })
HL("DevIconTerraform", { foreground = "#5F43E9" })
HL("DevIconTex", { foreground = "#3D6117" })
HL("DevIconTextResource", { foreground = "#CBCB41" })
HL("DevIconTextScene", { foreground = "#A074C4" })
HL("DevIconTor", { foreground = "#519ABA" })
HL("DevIconTrueTypeFont", { foreground = "#70C0BA" })
HL("DevIconTsx", { foreground = "#519ABA" })
HL("DevIconTwig", { foreground = "#8DC149" })
HL("DevIconTxt", { foreground = "#89E051" })
HL("DevIconVHDL", { foreground = "#019833" })
HL("DevIconVagrantfile", { foreground = "#1563FF" })
HL("DevIconVerilog", { foreground = "#019833" })
HL("DevIconVim", { foreground = "#79DCAA" })
HL("DevIconVimrc", { foreground = "#019833" })
HL("DevIconVue", { foreground = "#79E8AA" })
HL("DevIconWebOpenFontFormat", { foreground = "#76C6C0" })
HL("DevIconWebOpenFontFormat2", { foreground = "#76C6C0" })
HL("DevIconWebmanifest", { foreground = "#F1E05A" })
HL("DevIconWebp", { foreground = "#A074C4" })
HL("DevIconWebpack", { foreground = "#519ABA" })
HL("DevIconXZ", { foreground = "#36C692" })
HL("DevIconXcPlayground", { foreground = "#E37933" })
HL("DevIconXls", { foreground = "#207245" })
HL("DevIconXml", { foreground = "#E37933" })
HL("DevIconXul", { foreground = "#E37933" })
HL("DevIconYaml", { foreground = "#6D8086" })
HL("DevIconYml", { foreground = "#6D8086" })
HL("DevIconYuck", { foreground = "#FCCF67" })
HL("DevIconZig", { foreground = "#F69A1B" })
HL("DevIconZip", { foreground = "#36C692" })
HL("DevIconZsh", { foreground = "#89E051" })
HL("DevIconZshenv", { foreground = "#89E051" })
HL("DevIconZshprofile", { foreground = "#89E051" })
HL("DevIconZshrc", { foreground = "#89E051" })
HL("DevIconrobots", { foreground = "#54CED6" })
HL("DevIconsbt", { foreground = "#CC3E44" })
HL("DiagnosticError", { foreground = "#F87070" })
HL("DiagnosticFloatingError", { foreground = "#F87070" })
HL("DiagnosticFloatingHint", { foreground = "#C397D8" })
HL("DiagnosticFloatingInfo", { foreground = "#7AB0DF" })
HL("DiagnosticFloatingWarn", { foreground = "#F97F7F" })
HL("DiagnosticHint", { foreground = "#C397D8" })
HL("DiagnosticInfo", { foreground = "#7AB0DF" })
HL("DiagnosticSignError", { foreground = "#FB7373" })
HL("DiagnosticSignHint", { foreground = "#C397D8" })
HL("DiagnosticSignInfo", { foreground = "#7AB0DF" })
HL("DiagnosticSignWarn", { foreground = "#F97F7F" })
HL("DiagnosticUnderlineError", { foreground = "#F87070" })
HL("DiagnosticUnderlineHint", { foreground = "#C397D8" })
HL("DiagnosticUnderlineInfo", { foreground = "#7AB0DF" })
HL("DiagnosticUnderlineWarn", { foreground = "#F97F7F" })
HL("DiagnosticVirtualTextError", { foreground = "#F87070" })
HL("DiagnosticVirtualTextHint", { foreground = "#C397D8" })
HL("DiagnosticVirtualTextInfo", { foreground = "#7AB0DF" })
HL("DiagnosticVirtualTextWarn", { foreground = "#F97F7F" })
HL("DiagnosticWarn", { foreground = "#F97F7F" })
HL("DiffAdd", { foreground = "#79DCAA", reverse = true })
HL("DiffChange", { foreground = "#C397D8", reverse = true })
HL("DiffDelete", { foreground = "#F87070", reverse = true })
HL("DiffText", { foreground = "#7AB0DF", reverse = true })
HL("Directory", { foreground = "#FFE59E" })
HL("EndOfBuffer", { foreground = "#C397D8" })
HL("Error", { foreground = "#F76262" })
HL("ErrorMsg", { foreground = "#F87070" })
HL("Exception", { foreground = "#36C692" })
HL("FidgetTask", { foreground = "#1A1E27" })
HL("FidgetTitle", { bold = true, foreground = "#36C692" })
HL("Float", { foreground = "#F3A4F1" })
HL("FloatBorder", { background = "#151A1F", foreground = "#151A1F" })
HL("FloatShadow", { background = "#000000", blend = 80 })
HL("FloatShadowThrough", { background = "#000000", blend = 100 })
HL("FocusedSymbol", { background = "#666666", foreground = "#FFA0A0" })
HL("FoldColumn", { background = "#101317", foreground = "#70C0BA" })
HL("Folded", { background = "#101317", foreground = "#282F3C" })
HL("Function", { foreground = "#BE8FD7" })
HL("GitSignsAdd", { foreground = "#7AB0DF" })
HL("GitSignsAddInline", { reverse = true })
HL("GitSignsAddLn", { foreground = "#7AB0DF" })
HL("GitSignsAddLnInline", { reverse = true })
HL("GitSignsAddNr", { foreground = "#5FB0FC" })
HL("GitSignsAddPreview", { foreground = "#79DCAA", reverse = true })
HL("GitSignsChange", { foreground = "#21272D" })
HL("GitSignsChangeInline", { reverse = true })
HL("GitSignsChangeLn", { foreground = "#CB9FE0" })
HL("GitSignsChangeLnInline", { reverse = true })
HL("GitSignsChangeNr", { foreground = "#B77EE0" })
HL("GitSignsChangedelete", { foreground = "#21272D" })
HL("GitSignsChangedeleteLn", { foreground = "#CB9FE0" })
HL("GitSignsChangedeleteNr", { foreground = "#B77EE0" })
HL("GitSignsCurrentLineBlame", { foreground = "#222931" })
HL("GitSignsDelete", { foreground = "#FB7373" })
HL("GitSignsDeleteInline", { reverse = true })
HL("GitSignsDeleteLn", { foreground = "#F87070" })
HL("GitSignsDeleteLnInline", { reverse = true })
HL("GitSignsDeleteNr", { foreground = "#FE7676" })
HL("GitSignsDeletePreview", { foreground = "#F87070", reverse = true })
HL("GitSignsDeleteVirtLn", { foreground = "#F87070", reverse = true })
HL("GitSignsDeleteVirtLnInLine", { reverse = true })
HL("GitSignsStagedAdd", { foreground = "#3D586F" })
HL("GitSignsStagedAddLn", { foreground = "#3D586F" })
HL("GitSignsStagedAddNr", { foreground = "#2F587E" })
HL("GitSignsStagedChange", { foreground = "#101316" })
HL("GitSignsStagedChangeLn", { foreground = "#654F70" })
HL("GitSignsStagedChangeNr", { foreground = "#5B3F70" })
HL("GitSignsStagedChangedelete", { foreground = "#101316" })
HL("GitSignsStagedChangedeleteLn", { foreground = "#654F70" })
HL("GitSignsStagedChangedeleteNr", { foreground = "#5B3F70" })
HL("GitSignsStagedDelete", { foreground = "#7D3939" })
HL("GitSignsStagedDeleteLn", { foreground = "#7C3838" })
HL("GitSignsStagedDeleteNr", { foreground = "#7F3B3B" })
HL("GitSignsStagedTopdelete", { foreground = "#7D3939" })
HL("GitSignsStagedTopdeleteNr", { foreground = "#7F3B3B" })
HL("GitSignsTopdelete", { foreground = "#FB7373" })
HL("GitSignsTopdeleteNr", { foreground = "#FE7676" })
HL("GitSignsUntracked", { foreground = "#7AB0DF" })
HL("GitSignsUntrackedLn", { foreground = "#7AB0DF" })
HL("GitSignsUntrackedNr", { foreground = "#5FB0FC" })
HL("HlSearchFloat", { background = "#1A1E27", foreground = "#D0A4E5" })
HL("HlSearchLens", { background = "#1A1E27", foreground = "#87BDEC" })
HL("HlSearchLensNear", { background = "#FFE28F", bold = true, foreground = "#101317" })
HL("HlSearchNear", { background = "#1A1E27", bold = true, foreground = "#7DCDC7" })
HL("Identifier", { foreground = "#36C692" })
HL("IncSearch", { background = "#70C0BA", foreground = "#101317" })
HL("InclineNormal", { background = "#151A1F", foreground = "#BABABE" })
HL("InclineNormalNC", { background = "#151A1F", foreground = "#BABABE" })
HL("Include", { bold = true, foreground = "#6AA6DF" })
HL("IndentBlanklineChar", { foreground = "#22272C" })
HL("IndentBlanklineContextChar", { foreground = "#7AB0DF" })
HL("IndentBlanklineContextStart", { background = "#16191F" })
HL("IndentBlanklineSpaceChar", { foreground = "#1E222A", nocombine = true })
HL("IndentBlanklineSpaceCharBlankline", { foreground = "#1E222A", nocombine = true })
HL("Italic", { italic = true })
HL("Keyword", { foreground = "#66B3FF" })
HL("Label", { foreground = "#F87070" })
HL("LightBulbFloatWin", { foreground = "#FCCF67" })
HL("LightBulbSign", { foreground = "#FFE59E" })
HL("LightBulbVirtualText", { foreground = "#FFE59E" })
HL("LineNr", { foreground = "#2E3645" })
HL("LineNrAbove", { foreground = "#2E3645" })
HL("LineNrBelow", { foreground = "#2E3645" })
HL("LspDiagnosticsSignError", { foreground = "#FB7373" })
HL("LspDiagnosticsSignHint", { foreground = "#C397D8" })
HL("LspDiagnosticsSignInfo", { foreground = "#7AB0DF" })
HL("LspDiagnosticsSignWarn", { foreground = "#FF7D7D" })
HL("LspInfoBorder", { foreground = "#F87070" })
HL("LspInfoFiletype", { foreground = "#F87070" })
HL("LspInfoList", { foreground = "#BE8FD7" })
HL("LspInfoTip", { foreground = "#515C68" })
HL("LspInfoTitle", { bold = true, foreground = "#4B5259" })
HL("LspReferenceRead", { background = "#161921", bold = true, foreground = "#82B8E7" })
HL("LspReferenceText", { background = "#161921", bold = true, foreground = "#CB9FE0" })
HL("LspReferenceWrite", { background = "#161921", bold = true, foreground = "#DC97CA" })
HL("LspSignatureActiveParameter", { background = "#161921", bold = true, foreground = "#78C8C2" })
HL("Macro", { foreground = "#F98989" })
HL("MatchBackground", { background = "#111419", foreground = "#171A20" })
HL("MatchParen", { background = "#202530", bold = true })
HL("MatchParenCur", { background = "#202530", bold = true })
HL("MatchWord", { background = "#202530", bold = true })
HL("ModeMsg", { bold = true, foreground = "#7AB0DF" })
HL("MonarkCommand", { foreground = "#5FB0FC" })
HL("MonarkInsert", { foreground = "#7AB0DF" })
HL("MonarkReplace", { foreground = "#C397D8" })
HL("MonarkSelect", { foreground = "#54CED6" })
HL("MonarkTerminal", { foreground = "#54CED6" })
HL("MonarkVisual", { foreground = "#FFE59E" })
HL("MonarkVisualBlock", { foreground = "#FCCF67" })
HL("MonarkVisualLine", { foreground = "#F87070" })
HL("MoreMsg", { foreground = "#FFE59E" })
HL("MsgArea", { foreground = "#CACACD" })
HL("MsgSeparator", { foreground = "#C397D8" })
HL("NUICancel", { foreground = "#222931" })
HL("NUIHeading", { background = "#151A1F", foreground = "#F87070" })
HL("NUILine", { background = "#151A1F", foreground = "#22272C" })
HL("NUINo", { foreground = "#F87070" })
HL("NUINormal", { background = "#151A1F", foreground = "#151A1F" })
HL("NUIPrompt", { background = "#151A1F", foreground = "#7AB0DF" })
HL("NUIText", { background = "#151A1F", foreground = "#BABABE" })
HL("NUIYes", { foreground = "#7AB0DF" })
HL("NavicIconsArray", { foreground = "#FCCF67" })
HL("NavicIconsBoolean", { bold = true, foreground = "#F87070" })
HL("NavicIconsClass", { foreground = "#F75858" })
HL("NavicIconsConstant", { bold = true, foreground = "#FF6666" })
HL("NavicIconsConstructor", { foreground = "#5FB0FC" })
HL("NavicIconsEnum", { foreground = "#7AB0DF" })
HL("NavicIconsEnumMember", { foreground = "#F96262" })
HL("NavicIconsEvent", { foreground = "#79CFAA" })
HL("NavicIconsField", { foreground = "#36C692" })
HL("NavicIconsFile", { foreground = "#FFE59E" })
HL("NavicIconsFunction", { foreground = "#BE8FD7" })
HL("NavicIconsInterface", { foreground = "#FF7070" })
HL("NavicIconsKey", { foreground = "#F87070" })
HL("NavicIconsMethod", { foreground = "#B77EE0" })
HL("NavicIconsModule", { foreground = "#F98989" })
HL("NavicIconsNamespace", { foreground = "#60B0FC" })
HL("NavicIconsNull", { bold = true, foreground = "#FFDF85" })
HL("NavicIconsNumber", { foreground = "#54CED6" })
HL("NavicIconsObject", { foreground = "#FFE390" })
HL("NavicIconsOperator", { foreground = "#70C0BA" })
HL("NavicIconsPackage", { bold = true, foreground = "#6AA6DF" })
HL("NavicIconsProperty", { foreground = "#54CED6" })
HL("NavicIconsString", { foreground = "#79DCAA" })
HL("NavicIconsStruct", { foreground = "#5FB0FC" })
HL("NavicIconsTypeParameter", { foreground = "#FFE49D" })
HL("NavicIconsVariable", { bold = true, foreground = "#FA6969" })
HL("NavicSeparator", { foreground = "#7AB0DF" })
HL("NavicText", { foreground = "#AAAAAF" })
HL("NeogitBranch", { bold = true, foreground = "#36C692" })
HL("NeogitCommitViewHeader", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("NeogitDiffAdd", { background = "#16191D", foreground = "#7AB0DF" })
HL("NeogitDiffContextHighlight", { background = "#1A1D24" })
HL("NeogitDiffDelete", { background = "#1C1F22", foreground = "#F87070" })
HL("NeogitFilePath", { foreground = "#70C0BA" })
HL("NeogitFold", { foreground = "#54CED6" })
HL("NeogitHunkHeader", { background = "#171C21", foreground = "#FFE59E" })
HL("NeogitHunkHeaderHighlight", { background = "#FFE59E", foreground = "#101317" })
HL("NeogitNotificationError", { background = "#101317", foreground = "#F87070" })
HL("NeogitNotificationInfo", { background = "#101317", foreground = "#7AB0DF" })
HL("NeogitNotificationWarning", { background = "#101317", foreground = "#FFE59E" })
HL("NeogitObjectId", { foreground = "#C397D8" })
HL("NeogitRebaseDone", { bold = true, foreground = "#79DCAA" })
HL("NeogitRebasing", { bold = true, foreground = "#FFE59E" })
HL("NeogitRecentcommits", { bold = true, foreground = "#79DCAA" })
HL("NeogitRemote", { bold = true, foreground = "#FCCF67" })
HL("NeogitStagedchanges", { bold = true, foreground = "#FFE59E" })
HL("NeogitStash", { foreground = "#70C0BA" })
HL("NeogitStashes", { bold = true, foreground = "#70C0BA" })
HL("NeogitUnmergedInto", { foreground = "#7AB0DF" })
HL("NeogitUnmergedchanges", { bold = true, foreground = "#36C692" })
HL("NeogitUnpulledFrom", { foreground = "#54CED6" })
HL("NeogitUnpulledchanges", { bold = true, foreground = "#54CED6" })
HL("NeogitUnstagedchanges", { bold = true, foreground = "#FB7373" })
HL("NeogitUntrackedfiles", { bold = true, foreground = "#5FB0FC" })
HL("NonText", { foreground = "#222931" })
HL("Normal", { background = "#101317", foreground = "#D4D4D5" })
HL("NormalFloat", { background = "#151A1F", foreground = "#BABABE" })
HL("NotifyBackground", { background = "#101317", foreground = "#D4D4D5" })
HL("NotifyDEBUGBody", { background = "#171C21", foreground = "#C397D8" })
HL("NotifyDEBUGBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyDEBUGIcon", { background = "#171C21", foreground = "#B77EE0" })
HL("NotifyDEBUGTitle", { background = "#171C21", foreground = "#C397D8" })
HL("NotifyERRORBody", { background = "#171C21", foreground = "#F87070" })
HL("NotifyERRORBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyERRORIcon", { background = "#171C21", foreground = "#FB7373" })
HL("NotifyERRORTitle", { background = "#171C21", foreground = "#F87070" })
HL("NotifyINFOBody", { background = "#171C21", foreground = "#7AB0DF" })
HL("NotifyINFOBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyINFOIcon", { background = "#171C21", foreground = "#5FB0FC" })
HL("NotifyINFOTitle", { background = "#171C21", foreground = "#7AB0DF" })
HL("NotifyLogTime", { foreground = "#515C68" })
HL("NotifyLogTitle", { foreground = "#FB7373" })
HL("NotifyTRACEBody", { background = "#171C21", foreground = "#79DCAA" })
HL("NotifyTRACEBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyTRACEIcon", { background = "#171C21", foreground = "#36C692" })
HL("NotifyTRACETitle", { background = "#171C21", foreground = "#79DCAA" })
HL("NotifyWARNBody", { background = "#171C21", foreground = "#FFE59E" })
HL("NotifyWARNBorder", { background = "#171C21", foreground = "#171C21" })
HL("NotifyWARNIcon", { background = "#171C21", foreground = "#FCCF67" })
HL("NotifyWARNTitle", { background = "#171C21", foreground = "#FFE59E" })
HL("Number", { foreground = "#54CED6" })
HL("NvimAnd", { foreground = "#70C0BA" })
HL("NvimArrow", { foreground = "#FB7373" })
HL("NvimAssignment", { foreground = "#70C0BA" })
HL("NvimAssignmentWithAddition", { foreground = "#70C0BA" })
HL("NvimAssignmentWithConcatenation", { foreground = "#70C0BA" })
HL("NvimAssignmentWithSubtraction", { foreground = "#70C0BA" })
HL("NvimAugmentedAssignment", { foreground = "#70C0BA" })
HL("NvimBinaryMinus", { foreground = "#70C0BA" })
HL("NvimBinaryOperator", { foreground = "#70C0BA" })
HL("NvimBinaryPlus", { foreground = "#70C0BA" })
HL("NvimCallingParenthesis", { foreground = "#FB7373" })
HL("NvimColon", { foreground = "#FB7373" })
HL("NvimComma", { foreground = "#FB7373" })
HL("NvimComparison", { foreground = "#70C0BA" })
HL("NvimComparisonModifier", { foreground = "#70C0BA" })
HL("NvimConcat", { foreground = "#70C0BA" })
HL("NvimConcatOrSubscript", { foreground = "#70C0BA" })
HL("NvimContainer", { foreground = "#FB7373" })
HL("NvimCurly", { foreground = "#FB7373" })
HL("NvimDapSubtleFrame", { foreground = "#515C68" })
HL("NvimDict", { foreground = "#FB7373" })
HL("NvimDivision", { foreground = "#70C0BA" })
HL("NvimDoubleQuote", { foreground = "#79DCAA" })
HL("NvimDoubleQuotedBody", { foreground = "#79DCAA" })
HL("NvimDoubleQuotedEscape", { foreground = "#C397D8" })
HL("NvimDoubleQuotedUnknownEscape", { foreground = "#F76262" })
HL("NvimEnvironmentName", { foreground = "#36C692" })
HL("NvimEnvironmentSigil", { foreground = "#F87070" })
HL("NvimFigureBrace", { background = "#FF0000", foreground = "#FF0000" })
HL("NvimFloat", { foreground = "#54CED6" })
HL("NvimIdentifier", { foreground = "#36C692" })
HL("NvimIdentifierKey", { foreground = "#36C692" })
HL("NvimIdentifierName", { foreground = "#36C692" })
HL("NvimIdentifierScope", { foreground = "#36C692" })
HL("NvimIdentifierScopeDelimiter", { foreground = "#36C692" })
HL("NvimInternalError", { background = "#FF0000", foreground = "#FF0000" })
HL("NvimInvalid", { foreground = "#F76262" })
HL("NvimInvalidAnd", { foreground = "#F76262" })
HL("NvimInvalidArrow", { foreground = "#F76262" })
HL("NvimInvalidAssignment", { foreground = "#F76262" })
HL("NvimInvalidAssignmentWithAddition", { foreground = "#F76262" })
HL("NvimInvalidAssignmentWithConcatenation", { foreground = "#F76262" })
HL("NvimInvalidAssignmentWithSubtraction", { foreground = "#F76262" })
HL("NvimInvalidAugmentedAssignment", { foreground = "#F76262" })
HL("NvimInvalidBinaryMinus", { foreground = "#F76262" })
HL("NvimInvalidBinaryOperator", { foreground = "#F76262" })
HL("NvimInvalidBinaryPlus", { foreground = "#F76262" })
HL("NvimInvalidCallingParenthesis", { foreground = "#F76262" })
HL("NvimInvalidColon", { foreground = "#F76262" })
HL("NvimInvalidComma", { foreground = "#F76262" })
HL("NvimInvalidComparison", { foreground = "#F76262" })
HL("NvimInvalidComparisonModifier", { foreground = "#F76262" })
HL("NvimInvalidConcat", { foreground = "#F76262" })
HL("NvimInvalidConcatOrSubscript", { foreground = "#F76262" })
HL("NvimInvalidContainer", { foreground = "#F76262" })
HL("NvimInvalidCurly", { foreground = "#F76262" })
HL("NvimInvalidDelimiter", { foreground = "#F76262" })
HL("NvimInvalidDict", { foreground = "#F76262" })
HL("NvimInvalidDivision", { foreground = "#F76262" })
HL("NvimInvalidDoubleQuote", { foreground = "#F76262" })
HL("NvimInvalidDoubleQuotedBody", { foreground = "#79DCAA" })
HL("NvimInvalidDoubleQuotedEscape", { foreground = "#C397D8" })
HL("NvimInvalidDoubleQuotedUnknownEscape", { foreground = "#F76262" })
HL("NvimInvalidEnvironmentName", { foreground = "#F76262" })
HL("NvimInvalidEnvironmentSigil", { foreground = "#F76262" })
HL("NvimInvalidFigureBrace", { foreground = "#F76262" })
HL("NvimInvalidFloat", { foreground = "#F76262" })
HL("NvimInvalidIdentifier", { foreground = "#F76262" })
HL("NvimInvalidIdentifierKey", { foreground = "#F76262" })
HL("NvimInvalidIdentifierName", { foreground = "#F76262" })
HL("NvimInvalidIdentifierScope", { foreground = "#F76262" })
HL("NvimInvalidIdentifierScopeDelimiter", { foreground = "#F76262" })
HL("NvimInvalidLambda", { foreground = "#F76262" })
HL("NvimInvalidList", { foreground = "#F76262" })
HL("NvimInvalidMod", { foreground = "#F76262" })
HL("NvimInvalidMultiplication", { foreground = "#F76262" })
HL("NvimInvalidNestingParenthesis", { foreground = "#F76262" })
HL("NvimInvalidNot", { foreground = "#F76262" })
HL("NvimInvalidNumber", { foreground = "#F76262" })
HL("NvimInvalidNumberPrefix", { foreground = "#F76262" })
HL("NvimInvalidOperator", { foreground = "#F76262" })
HL("NvimInvalidOptionName", { foreground = "#F76262" })
HL("NvimInvalidOptionScope", { foreground = "#F76262" })
HL("NvimInvalidOptionScopeDelimiter", { foreground = "#F76262" })
HL("NvimInvalidOptionSigil", { foreground = "#F76262" })
HL("NvimInvalidOr", { foreground = "#F76262" })
HL("NvimInvalidParenthesis", { foreground = "#F76262" })
HL("NvimInvalidPlainAssignment", { foreground = "#F76262" })
HL("NvimInvalidRegister", { foreground = "#F76262" })
HL("NvimInvalidSingleQuote", { foreground = "#F76262" })
HL("NvimInvalidSingleQuotedBody", { foreground = "#79DCAA" })
HL("NvimInvalidSingleQuotedQuote", { foreground = "#C397D8" })
HL("NvimInvalidSingleQuotedUnknownEscape", { background = "#FF0000", foreground = "#FF0000" })
HL("NvimInvalidSpacing", { foreground = "#F87070" })
HL("NvimInvalidString", { foreground = "#F76262" })
HL("NvimInvalidStringBody", { foreground = "#79DCAA" })
HL("NvimInvalidStringQuote", { foreground = "#F76262" })
HL("NvimInvalidStringSpecial", { foreground = "#C397D8" })
HL("NvimInvalidSubscript", { foreground = "#F76262" })
HL("NvimInvalidSubscriptBracket", { foreground = "#F76262" })
HL("NvimInvalidSubscriptColon", { foreground = "#F76262" })
HL("NvimInvalidTernary", { foreground = "#F76262" })
HL("NvimInvalidTernaryColon", { foreground = "#F76262" })
HL("NvimInvalidUnaryMinus", { foreground = "#F76262" })
HL("NvimInvalidUnaryOperator", { foreground = "#F76262" })
HL("NvimInvalidUnaryPlus", { foreground = "#F76262" })
HL("NvimInvalidValue", { foreground = "#F76262" })
HL("NvimLambda", { foreground = "#FB7373" })
HL("NvimList", { foreground = "#FB7373" })
HL("NvimMod", { foreground = "#70C0BA" })
HL("NvimMultiplication", { foreground = "#70C0BA" })
HL("NvimNestingParenthesis", { foreground = "#FB7373" })
HL("NvimNot", { foreground = "#70C0BA" })
HL("NvimNumber", { foreground = "#54CED6" })
HL("NvimNumberPrefix", { foreground = "#F87070" })
HL("NvimOperator", { foreground = "#70C0BA" })
HL("NvimOptionName", { foreground = "#36C692" })
HL("NvimOptionScope", { foreground = "#36C692" })
HL("NvimOptionScopeDelimiter", { foreground = "#36C692" })
HL("NvimOptionSigil", { foreground = "#F87070" })
HL("NvimOr", { foreground = "#70C0BA" })
HL("NvimParenthesis", { foreground = "#FB7373" })
HL("NvimPlainAssignment", { foreground = "#70C0BA" })
HL("NvimRegister", { foreground = "#C397D8" })
HL("NvimSingleQuote", { foreground = "#79DCAA" })
HL("NvimSingleQuotedBody", { foreground = "#79DCAA" })
HL("NvimSingleQuotedQuote", { foreground = "#C397D8" })
HL("NvimSingleQuotedUnknownEscape", { background = "#FF0000", foreground = "#FF0000" })
HL("NvimSpacing", { background = "#101317", foreground = "#D4D4D5" })
HL("NvimString", { foreground = "#79DCAA" })
HL("NvimStringBody", { foreground = "#79DCAA" })
HL("NvimStringQuote", { foreground = "#79DCAA" })
HL("NvimStringSpecial", { foreground = "#C397D8" })
HL("NvimSubscript", { foreground = "#FB7373" })
HL("NvimSubscriptBracket", { foreground = "#FB7373" })
HL("NvimSubscriptColon", { foreground = "#FB7373" })
HL("NvimTernary", { foreground = "#70C0BA" })
HL("NvimTernaryColon", { foreground = "#70C0BA" })
HL("NvimTreeBookmark", { foreground = "#FFE59E" })
HL("NvimTreeClosedFolderIcon", { foreground = "#B77EE0" })
HL("NvimTreeCursorLine", { foreground = "#12151B" })
HL("NvimTreeCursorLineNr", { bold = true, foreground = "#7AB0DF" })
HL("NvimTreeEmptyFolderName", { foreground = "#B58ED1" })
HL("NvimTreeExecFile", { foreground = "#D997C8" })
HL("NvimTreeFileDeleted", { foreground = "#FB7373" })
HL("NvimTreeFileDirty", { foreground = "#70C0BA" })
HL("NvimTreeFileIgnored", { foreground = "#171C21" })
HL("NvimTreeFileMerge", { foreground = "#36C692" })
HL("NvimTreeFileNew", { foreground = "#FFE59E" })
HL("NvimTreeFileRenamed", { foreground = "#5FB0FC" })
HL("NvimTreeFileStaged", { foreground = "#D997C8" })
HL("NvimTreeFolderIcon", { foreground = "#B77EE0" })
HL("NvimTreeFolderName", { foreground = "#B77EE0" })
HL("NvimTreeGitDeleted", { foreground = "#F87070" })
HL("NvimTreeGitDirty", { foreground = "#70C0BA" })
HL("NvimTreeGitIgnored", { foreground = "#171C21" })
HL("NvimTreeGitMerge", { foreground = "#54CED6" })
HL("NvimTreeGitNew", { foreground = "#FFE59E" })
HL("NvimTreeGitRenamed", { foreground = "#5FB0FC" })
HL("NvimTreeGitStaged", { foreground = "#D997C8" })
HL("NvimTreeImageFile", { foreground = "#B77EE0" })
HL("NvimTreeIndentMarker", { foreground = "#1D2529" })
HL("NvimTreeNormal", { background = "#0C0E11", foreground = "#BABABE" })
HL("NvimTreeNormalNC", { background = "#0C0E11", foreground = "#BABABE" })
HL("NvimTreePopup", { foreground = "#7AB0DF" })
HL("NvimTreeRootFolder", { bold = true, foreground = "#F87070" })
HL("NvimTreeSymlink", { foreground = "#70C0BA" })
HL("NvimTreeVertSplit", { background = "#0C0E11", foreground = "#0C0E11" })
HL("NvimTreeWinSeparator", { background = "#0C0E11", foreground = "#0C0E11" })
HL("NvimTreeWindowPicker", { background = "#191C24", foreground = "#7AB0DF" })
HL("NvimUnaryMinus", { foreground = "#70C0BA" })
HL("NvimUnaryOperator", { foreground = "#70C0BA" })
HL("NvimUnaryPlus", { foreground = "#70C0BA" })
HL("Operator", { foreground = "#70C0BA" })
HL("Pmenu", { background = "#171D20", foreground = "#A0A0A5" })
HL("PmenuSbar", { background = "#171D20", foreground = "#A0A0A5" })
HL("PmenuSel", { background = "#79DCAA", foreground = "#101317" })
HL("PmenuThumb", { background = "#1E2225" })
HL("PreCondit", { foreground = "#F96262" })
HL("PreProc", { foreground = "#F96262" })
HL("Question", { foreground = "#79DCAA" })
HL("QuickFixLine", { background = "#FFE59E", foreground = "#101317" })
HL("RedrawDebugClear", { background = "#FFFF00" })
HL("RedrawDebugComposed", { background = "#008000" })
HL("RedrawDebugNormal", { reverse = true })
HL("RedrawDebugRecompose", { background = "#FF0000" })
HL("Repeat", { foreground = "#B77EE0" })
HL("RnvimrCurses", { background = "#101317", foreground = "#D4D4D5" })
HL("RnvimrNormal", { background = "#151A1F", foreground = "#BABABE" })
HL("ScrollbarCursor", { foreground = "#54CED6" })
HL("ScrollbarCursorHandle", { background = "#20272E", foreground = "#54CED6" })
HL("ScrollbarError", { foreground = "#F87070" })
HL("ScrollbarErrorHandle", { foreground = "#F87070" })
HL("ScrollbarGitAdd", { foreground = "#7AB0DF" })
HL("ScrollbarGitAddHandle", { foreground = "#82B8E7" })
HL("ScrollbarGitChange", { foreground = "#C397D8" })
HL("ScrollbarGitChangeHandle", { foreground = "#BD84E6" })
HL("ScrollbarGitDelete", { foreground = "#F87070" })
HL("ScrollbarGitDeleteHandle", { foreground = "#FF7B7B" })
HL("ScrollbarHandle", { foreground = "#7AB0DF" })
HL("ScrollbarHint", { foreground = "#C397D8" })
HL("ScrollbarHintHandle", { foreground = "#B77EE0" })
HL("ScrollbarInfo", { foreground = "#7AB0DF" })
HL("ScrollbarInfoHandle", { foreground = "#7AB0DF" })
HL("ScrollbarMisc", { foreground = "#DC97CA" })
HL("ScrollbarMiscHandle", { foreground = "#70C0BA" })
HL("ScrollbarSearch", { foreground = "#FFE59E" })
HL("ScrollbarSearchHandle", { foreground = "#FFD76F" })
HL("ScrollbarWarn", { foreground = "#F97F7F" })
HL("ScrollbarWarnHandle", { foreground = "#FA6969" })
HL("Search", { background = "#FFE59E", foreground = "#101317" })
HL("SignColumn", { background = "#101317" })
HL("Special", { foreground = "#FB7373" })
HL("SpecialChar", { foreground = "#C397D8" })
HL("SpecialComment", { foreground = "#FFDF8F" })
HL("SpecialKey", { bold = true, foreground = "#FFE59E" })
HL("SpellBad", { foreground = "#F87070" })
HL("SpellCap", { foreground = "#FCCF67" })
HL("SpellLocal", { foreground = "#FB7373" })
HL("SpellRare", { foreground = "#54CED6" })
HL("Statement", { foreground = "#F87070" })
HL("StatusComponent_1C212A_1C212A_NONE", { background = "#1C212A", foreground = "#1C212A" })
HL("StatusComponent_1C212A_5FB0FC_bold", { background = "#5FB0FC", bold = true, foreground = "#1C212A" })
HL("StatusComponent_1C212A_79DCAA_bold", { background = "#79DCAA", bold = true, foreground = "#1C212A" })
HL("StatusComponent_1C212A_7AB0DF_bold", { background = "#7AB0DF", bold = true, foreground = "#1C212A" })
HL("StatusComponent_222730_1C212A_NONE", { background = "#1C212A", foreground = "#222730" })
HL("StatusComponent_5FB0FC_1C212A_NONE", { background = "#1C212A", foreground = "#5FB0FC" })
HL("StatusComponent_79DCAA_1C212A_NONE", { background = "#1C212A", foreground = "#79DCAA" })
HL("StatusComponent_79DCAA_222730_bold", { background = "#222730", bold = true, foreground = "#79DCAA" })
HL("StatusComponent_7AB0DF_1C212A_NONE", { background = "#1C212A", foreground = "#7AB0DF" })
HL("StatusComponent_7AB0DF_1C212A_bold", { background = "#1C212A", bold = true, foreground = "#7AB0DF" })
HL("StatusComponent_7ab0df_222730_NONE", { background = "#222730", foreground = "#7AB0DF" })
HL("StatusComponent_C397D8_1C212A_NONE", { background = "#1C212A", foreground = "#C397D8" })
HL("StatusComponent_C397D8_1C212A_bold", { background = "#1C212A", bold = true, foreground = "#C397D8" })
HL("StatusComponent_C7C7CA_1C212A_NONE", { background = "#1C212A", foreground = "#C7C7CA" })
HL("StatusComponent_C7C7CA_1C212A_bold", { background = "#1C212A", bold = true, foreground = "#C7C7CA" })
HL("StatusComponent_C7C7CA_222730_NONE", { background = "#222730", foreground = "#C7C7CA" })
HL("StatusComponent_F87070_1C212A_NONE", { background = "#1C212A", foreground = "#F87070" })
HL("StatusComponent_F87070_1C212A_bold", { background = "#1C212A", bold = true, foreground = "#F87070" })
HL("StatusComponent_FFE59E_1C212A_NONE", { background = "#1C212A", foreground = "#FFE59E" })
HL("StatusComponent_FFE59E_222730_bold", { background = "#222730", bold = true, foreground = "#FFE59E" })
HL("StatusLine", { background = "#101317", foreground = "#7AB0DF" })
HL("StatusLineNC", { foreground = "#7AB0DF" })
HL("StorageClass", { foreground = "#F75858" })
HL("String", { foreground = "#79DCAA" })
HL("Structure", { foreground = "#5FB0FC" })
HL("Substitute", { background = "#B77EE0", foreground = "#101317" })
HL("SymbolsOutlineConnector", { foreground = "#80A0FF" })
HL("TabLine", { background = "#101317", bold = true, foreground = "#2C3640" })
HL("TabLineFill", { background = "#101317", foreground = "#7AB0DF" })
HL("TabLineSel", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("Tag", { foreground = "#7AB0DF" })
HL("TelescopeBorder", { background = "#101317", foreground = "#D4D4D5" })
HL("TelescopeMatching", { bold = true, foreground = "#DC97CA" })
HL("TelescopeMultiIcon", { foreground = "#36C692" })
HL("TelescopeMultiSelection", { foreground = "#F87070" })
HL("TelescopeNormal", { background = "#101317", foreground = "#D4D4D5" })
HL("TelescopePreviewBlock", { foreground = "#FF6666" })
HL("TelescopePreviewBorder", { background = "#0E1014", foreground = "#0E1014" })
HL("TelescopePreviewCharDev", { foreground = "#FF6666" })
HL("TelescopePreviewDate", { foreground = "#FFE59E" })
HL("TelescopePreviewDirectory", { foreground = "#FFE59E" })
HL("TelescopePreviewExecute", { foreground = "#79DCAA" })
HL("TelescopePreviewGroup", { foreground = "#FF6666" })
HL("TelescopePreviewHyphen", { foreground = "#222931" })
HL("TelescopePreviewLine", { background = "#16191F" })
HL("TelescopePreviewLink", { foreground = "#FB7373" })
HL("TelescopePreviewMatch", { background = "#FFE59E", foreground = "#101317" })
HL("TelescopePreviewMessage", { background = "#0E1014", foreground = "#BABABE" })
HL("TelescopePreviewMessageFillchar", { background = "#0E1014", foreground = "#BABABE" })
HL("TelescopePreviewNormal", { background = "#0E1014", foreground = "#BABABE" })
HL("TelescopePreviewPipe", { foreground = "#FF6666" })
HL("TelescopePreviewRead", { foreground = "#FF6666" })
HL("TelescopePreviewSize", { foreground = "#79DCAA" })
HL("TelescopePreviewSocket", { foreground = "#F87070" })
HL("TelescopePreviewSticky", { foreground = "#66B3FF" })
HL("TelescopePreviewTitle", { background = "#7AB0DF", foreground = "#101317" })
HL("TelescopePreviewUser", { foreground = "#FF6666" })
HL("TelescopePreviewWrite", { foreground = "#F87070" })
HL("TelescopePromptBorder", { background = "#14191D", foreground = "#14191D" })
HL("TelescopePromptCounter", { background = "#14191D", bold = true, foreground = "#D997C8" })
HL("TelescopePromptNormal", { background = "#14191D", foreground = "#BABABE" })
HL("TelescopePromptPrefix", { background = "#14191D", foreground = "#F87070" })
HL("TelescopePromptTitle", { background = "#F87070", foreground = "#101317" })
HL("TelescopeResultsBorder", { background = "#0C0E11", foreground = "#0C0E11" })
HL("TelescopeResultsClass", { foreground = "#BE8FD7" })
HL("TelescopeResultsComment", { foreground = "#515C68" })
HL("TelescopeResultsConstant", { foreground = "#FF6666" })
HL("TelescopeResultsDiffAdd", { foreground = "#79DCAA", reverse = true })
HL("TelescopeResultsDiffChange", { foreground = "#C397D8", reverse = true })
HL("TelescopeResultsDiffDelete", { foreground = "#F87070", reverse = true })
HL("TelescopeResultsDiffUntracked", { foreground = "#222931" })
HL("TelescopeResultsField", { foreground = "#BE8FD7" })
HL("TelescopeResultsFunction", { foreground = "#BE8FD7" })
HL("TelescopeResultsIdentifier", { foreground = "#36C692" })
HL("TelescopeResultsLineNr", { foreground = "#2E3645" })
HL("TelescopeResultsNormal", { background = "#0C0E11", foreground = "#BABABE" })
HL("TelescopeResultsNumber", { foreground = "#54CED6" })
HL("TelescopeResultsOperator", { foreground = "#70C0BA" })
HL("TelescopeResultsSpecialComment", { foreground = "#FFDF8F" })
HL("TelescopeResultsTitle", { background = "#79DCAA", foreground = "#101317" })
HL("TelescopeResultsVariable", { foreground = "#C397D8" })
HL("TelescopeSelection", { background = "#101317", foreground = "#54CED6" })
HL("TelescopeSelectionCaret", { background = "#101317", foreground = "#FB7373" })
HL("TelescopeTitle", { background = "#101317", foreground = "#D4D4D5" })
HL("TermCursor", { reverse = true })
HL("Title", { bold = true, foreground = "#4B5259" })
HL("Todo", { foreground = "#FFE59E" })
HL("TodoBgBUG", { background = "#F87070", foreground = "#171C21" })
HL("TodoBgCHORE", { background = "#70C0BA", foreground = "#171C21" })
HL("TodoBgCLEAN", { background = "#7AB0DF", foreground = "#171C21" })
HL("TodoBgDEMO", { background = "#5FB0FC", foreground = "#171C21" })
HL("TodoBgFIX", { background = "#FFE59E", foreground = "#171C21" })
HL("TodoBgHACK", { background = "#79DCAA", foreground = "#171C21" })
HL("TodoBgIMPROVE", { background = "#5FB0FC", foreground = "#171C21" })
HL("TodoBgNOTE", { background = "#36C692", foreground = "#171C21" })
HL("TodoBgPERF", { background = "#FCCF67", foreground = "#171C21" })
HL("TodoBgTEST", { background = "#54CED6", foreground = "#171C21" })
HL("TodoBgTODO", { background = "#C397D8", foreground = "#171C21" })
HL("TodoBgUPDATE", { background = "#B77EE0", foreground = "#171C21" })
HL("TodoBgWANTS", { background = "#FFEDA6", foreground = "#171C21" })
HL("TodoBgWARN", { background = "#E17272", foreground = "#171C21" })
HL("TodoFgBUG", { foreground = "#F87070" })
HL("TodoFgCHORE", { foreground = "#70C0BA" })
HL("TodoFgCLEAN", { foreground = "#7AB0DF" })
HL("TodoFgDEMO", { foreground = "#5FB0FC" })
HL("TodoFgFIX", { foreground = "#FFE59E" })
HL("TodoFgHACK", { foreground = "#79DCAA" })
HL("TodoFgIMPROVE", { foreground = "#5FB0FC" })
HL("TodoFgNOTE", { foreground = "#36C692" })
HL("TodoFgPERF", { foreground = "#FCCF67" })
HL("TodoFgTEST", { foreground = "#54CED6" })
HL("TodoFgTODO", { foreground = "#C397D8" })
HL("TodoFgUPDATE", { foreground = "#B77EE0" })
HL("TodoFgWANTS", { foreground = "#FFEDA6" })
HL("TodoFgWARN", { foreground = "#E17272" })
HL("TodoSignBUG", { background = "#101317", foreground = "#F87070" })
HL("TodoSignCHORE", { background = "#101317", foreground = "#70C0BA" })
HL("TodoSignCLEAN", { background = "#101317", foreground = "#7AB0DF" })
HL("TodoSignDEMO", { background = "#101317", foreground = "#5FB0FC" })
HL("TodoSignFIX", { background = "#101317", foreground = "#FCCF67" })
HL("TodoSignHACK", { background = "#101317", foreground = "#79DCAA" })
HL("TodoSignIMPROVE", { background = "#101317", foreground = "#5FB0FC" })
HL("TodoSignNOTE", { background = "#101317", foreground = "#36C692" })
HL("TodoSignPERF", { background = "#101317", foreground = "#FCCF67" })
HL("TodoSignTEST", { background = "#101317", foreground = "#54CED6" })
HL("TodoSignTODO", { background = "#101317", foreground = "#C397D8" })
HL("TodoSignUPDATE", { background = "#101317", foreground = "#B77EE0" })
HL("TodoSignWANTS", { background = "#101317", foreground = "#FFEDA6" })
HL("TodoSignWARN", { background = "#101317", foreground = "#E17272" })
HL("ToggleTerm1FloatBorder", { background = "#151A1F", foreground = "#151A1F" })
HL("ToggleTerm1NormalFloat", { background = "#151A1F", foreground = "#BABABE" })
HL("TreesitterContext", { background = "#171A20" })
HL("TreesitterContextLineNumber", { foreground = "#2E3645" })
HL("TroubleCode", { foreground = "#515C68" })
HL("TroubleCount", { background = "#7AB0DF", bold = true, foreground = "#101317" })
HL("TroubleError", { foreground = "#F87070" })
HL("TroubleFile", { foreground = "#FFE59E" })
HL("TroubleFoldIcon", { bold = true, foreground = "#FFE59E" })
HL("TroubleHint", { foreground = "#C397D8" })
HL("TroubleIndent", { foreground = "#2E3645" })
HL("TroubleInformation", { foreground = "#7AB0DF" })
HL("TroubleLocation", { foreground = "#2E3645" })
HL("TroubleNormal", { background = "#0C0E11" })
HL("TroublePreview", { background = "#FFE59E", foreground = "#101317" })
HL("TroubleSignError", { foreground = "#FB7373" })
HL("TroubleSignHint", { foreground = "#C397D8" })
HL("TroubleSignInformation", { foreground = "#7AB0DF" })
HL("TroubleSignOther", { foreground = "#7AB0DF" })
HL("TroubleSignWarning", { foreground = "#F97F7F" })
HL("TroubleSource", { foreground = "#515C68" })
HL("TroubleText", { background = "#101317", foreground = "#D4D4D5" })
HL("TroubleTextError", { background = "#101317", foreground = "#D4D4D5" })
HL("TroubleTextHint", { background = "#101317", foreground = "#D4D4D5" })
HL("TroubleTextInformation", { background = "#101317", foreground = "#D4D4D5" })
HL("TroubleTextWarning", { background = "#101317", foreground = "#D4D4D5" })
HL("TroubleWarning", { foreground = "#F97F7F" })
HL("Type", { foreground = "#F87070" })
HL("Typedef", { foreground = "#C397D8" })
HL("Underlined", { underline = true })
HL("UndotreeBranch", { foreground = "#FF6666" })
HL("UndotreeCurrent", { foreground = "#F87070" })
HL("UndotreeFirstNode", { foreground = "#BE8FD7" })
HL("UndotreeHead", { foreground = "#36C692" })
HL("UndotreeHelp", { foreground = "#515C68" })
HL("UndotreeHelpKey", { bold = true, foreground = "#F87070" })
HL("UndotreeHelpTitle", { foreground = "#F87070" })
HL("UndotreeNext", { foreground = "#7AB0DF" })
HL("UndotreeNode", { foreground = "#79DCAA" })
HL("UndotreeNodeCurrent", { foreground = "#E1C58D" })
HL("UndotreeSavedBig", { background = "#202530", bold = true })
HL("UndotreeSavedSmall", { foreground = "#FB7373" })
HL("UndotreeSeq", { foreground = "#515C68" })
HL("UndotreeTimeStamp", { foreground = "#70C0BA" })
HL("VertSplit", { foreground = "#171C21" })
HL("VirtColumn", { background = "#101317", foreground = "#171A20" })
HL("Visual", { background = "#192023" })
HL("WarningMsg", { foreground = "#FB7373" })
HL("WhichKey", { foreground = "#C397D8" })
HL("WhichKeyBorder", { background = "#0E1014" })
HL("WhichKeyDesc", { foreground = "#FFE59E" })
HL("WhichKeyFloat", { background = "#0E1014" })
HL("WhichKeyGroup", { bold = true, foreground = "#F87070" })
HL("WhichKeySeparator", { foreground = "#7AB0DF" })
HL("WhichKeyValue", { foreground = "#929299" })
HL("Whitespace", { foreground = "#1E222A" })
HL("WildMenu", { background = "#7AB0DF", foreground = "#101317" })
HL("WinBar", { bold = true })
HL("WinBarNC", { bold = true })
HL("WinSeparator", { foreground = "#171C21" })
HL("cssAnimationAttr", { foreground = "#FF6666" })
HL("cssAnimationProp", { foreground = "#F75858" })
HL("cssAtKeyword", { foreground = "#F96262" })
HL("cssAtRule", { bold = true, foreground = "#6AA6DF" })
HL("cssAtRuleLogical", { foreground = "#F87070" })
HL("cssAttr", { foreground = "#FF6666" })
HL("cssAttrComma", { foreground = "#FB7373" })
HL("cssAttributeSelector", { foreground = "#79DCAA" })
HL("cssAuralAttr", { foreground = "#FF6666" })
HL("cssAuralProp", { foreground = "#F75858" })
HL("cssBackgroundAttr", { foreground = "#FF6666" })
HL("cssBackgroundProp", { foreground = "#F75858" })
HL("cssBorderAttr", { foreground = "#FF6666" })
HL("cssBorderProp", { foreground = "#F75858" })
HL("cssBoxAttr", { foreground = "#FF6666" })
HL("cssBoxProp", { foreground = "#F75858" })
HL("cssBraceError", { foreground = "#F76262" })
HL("cssBraces", { foreground = "#BE8FD7" })
HL("cssCascadeAttr", { foreground = "#FF6666" })
HL("cssCascadeProp", { foreground = "#F75858" })
HL("cssClassName", { foreground = "#BE8FD7" })
HL("cssClassNameDot", { foreground = "#BE8FD7" })
HL("cssColor", { foreground = "#FF6666" })
HL("cssColorProp", { foreground = "#F75858" })
HL("cssComment", { foreground = "#515C68" })
HL("cssCommonAttr", { foreground = "#FF6666" })
HL("cssContentForPagedMediaAttr", { foreground = "#FF6666" })
HL("cssContentForPagedMediaProp", { foreground = "#F75858" })
HL("cssCustomProp", { foreground = "#FB7373" })
HL("cssDeprecated", { foreground = "#F76262" })
HL("cssDimensionAttr", { foreground = "#FF6666" })
HL("cssDimensionProp", { foreground = "#F75858" })
HL("cssError", { foreground = "#F76262" })
HL("cssFlexibleBoxAttr", { foreground = "#FF6666" })
HL("cssFlexibleBoxProp", { foreground = "#F75858" })
HL("cssFontAttr", { foreground = "#FF6666" })
HL("cssFontDescriptor", { foreground = "#FB7373" })
HL("cssFontDescriptorAttr", { foreground = "#FF6666" })
HL("cssFontDescriptorProp", { foreground = "#F75858" })
HL("cssFontProp", { foreground = "#F75858" })
HL("cssFunction", { foreground = "#FF6666" })
HL("cssFunctionComma", { foreground = "#BE8FD7" })
HL("cssFunctionName", { foreground = "#BE8FD7" })
HL("cssGeneratedContentAttr", { foreground = "#FF6666" })
HL("cssGeneratedContentProp", { foreground = "#F75858" })
HL("cssGradientAttr", { foreground = "#FF6666" })
HL("cssGridAttr", { foreground = "#FF6666" })
HL("cssGridProp", { foreground = "#F75858" })
HL("cssHacks", { foreground = "#515C68" })
HL("cssHyerlinkAttr", { foreground = "#FF6666" })
HL("cssHyerlinkProp", { foreground = "#F75858" })
HL("cssIEUIAttr", { foreground = "#FF6666" })
HL("cssIEUIProp", { foreground = "#F75858" })
HL("cssIdentifier", { foreground = "#BE8FD7" })
HL("cssImportant", { foreground = "#FB7373" })
HL("cssInteractAttr", { foreground = "#FF6666" })
HL("cssInteractProp", { foreground = "#F75858" })
HL("cssKeyFrameProp", { foreground = "#FF6666" })
HL("cssLineboxAttr", { foreground = "#FF6666" })
HL("cssLineboxProp", { foreground = "#F75858" })
HL("cssListAttr", { foreground = "#FF6666" })
HL("cssListProp", { foreground = "#F75858" })
HL("cssMarginAttr", { foreground = "#FF6666" })
HL("cssMarqueeAttr", { foreground = "#FF6666" })
HL("cssMarqueeProp", { foreground = "#F75858" })
HL("cssMediaAttr", { foreground = "#FF6666" })
HL("cssMediaComma", { background = "#101317", foreground = "#D4D4D5" })
HL("cssMediaProp", { foreground = "#F75858" })
HL("cssMediaType", { foreground = "#FB7373" })
HL("cssMobileTextProp", { foreground = "#F75858" })
HL("cssMultiColumnAttr", { foreground = "#FF6666" })
HL("cssMultiColumnProp", { foreground = "#F75858" })
HL("cssObjectAttr", { foreground = "#FF6666" })
HL("cssObjectProp", { foreground = "#F75858" })
HL("cssPaddingAttr", { foreground = "#FF6666" })
HL("cssPageMarginProp", { foreground = "#F96262" })
HL("cssPageProp", { foreground = "#F75858" })
HL("cssPagePseudo", { foreground = "#F96262" })
HL("cssPagedMediaAttr", { foreground = "#FF6666" })
HL("cssPagedMediaProp", { foreground = "#F75858" })
HL("cssPositioningAttr", { foreground = "#FF6666" })
HL("cssPositioningProp", { foreground = "#F75858" })
HL("cssPrintAttr", { foreground = "#FF6666" })
HL("cssPrintProp", { foreground = "#F75858" })
HL("cssProp", { foreground = "#F75858" })
HL("cssPseudoClassId", { foreground = "#F96262" })
HL("cssPseudoClassLang", { foreground = "#FF6666" })
HL("cssRenderAttr", { foreground = "#FF6666" })
HL("cssRenderProp", { foreground = "#F75858" })
HL("cssRubyAttr", { foreground = "#FF6666" })
HL("cssRubyProp", { foreground = "#F75858" })
HL("cssSelectorOp", { foreground = "#FB7373" })
HL("cssSelectorOp2", { foreground = "#FB7373" })
HL("cssSpeechAttr", { foreground = "#FF6666" })
HL("cssSpeechProp", { foreground = "#F75858" })
HL("cssStringQ", { foreground = "#79DCAA" })
HL("cssStringQQ", { foreground = "#79DCAA" })
HL("cssTableAttr", { foreground = "#FF6666" })
HL("cssTableProp", { foreground = "#F75858" })
HL("cssTagName", { foreground = "#F87070" })
HL("cssTextAttr", { foreground = "#FF6666" })
HL("cssTextProp", { foreground = "#F75858" })
HL("cssTransformAttr", { foreground = "#FF6666" })
HL("cssTransformProp", { foreground = "#F75858" })
HL("cssTransitionAttr", { foreground = "#FF6666" })
HL("cssTransitionProp", { foreground = "#F75858" })
HL("cssUIAttr", { foreground = "#FF6666" })
HL("cssUIProp", { foreground = "#F75858" })
HL("cssURL", { foreground = "#79DCAA" })
HL("cssUnicodeEscape", { foreground = "#FB7373" })
HL("cssUnicodeRange", { foreground = "#FF6666" })
HL("cssUnitDecorators", { foreground = "#54CED6" })
HL("cssValueAngle", { foreground = "#54CED6" })
HL("cssValueFrequency", { foreground = "#54CED6" })
HL("cssValueInteger", { foreground = "#54CED6" })
HL("cssValueLength", { foreground = "#54CED6" })
HL("cssValueNumber", { foreground = "#54CED6" })
HL("cssValueTime", { foreground = "#54CED6" })
HL("cssVendor", { foreground = "#515C68" })
HL("dtdAttrDef", { foreground = "#F87070" })
HL("dtdAttrType", { foreground = "#F87070" })
HL("dtdCard", { foreground = "#BE8FD7" })
HL("dtdComment", { foreground = "#515C68" })
HL("dtdConstant", { foreground = "#FF6666" })
HL("dtdEntity", { foreground = "#F87070" })
HL("dtdEntityPunct", { foreground = "#F87070" })
HL("dtdEnum", { foreground = "#FF6666" })
HL("dtdError", { foreground = "#F76262" })
HL("dtdFunction", { foreground = "#BE8FD7" })
HL("dtdParamEntityDPunct", { foreground = "#515C68" })
HL("dtdParamEntityDecl", { foreground = "#F87070" })
HL("dtdParamEntityInst", { foreground = "#FF6666" })
HL("dtdParamEntityPunct", { foreground = "#F87070" })
HL("dtdString", { foreground = "#FF6666" })
HL("dtdTag", { background = "#101317", foreground = "#D4D4D5" })
HL("dtdTagName", { foreground = "#F87070" })
HL("dtdTodo", { foreground = "#FFE59E" })
HL("dtdType", { foreground = "#F87070" })
HL("htmlArg", { foreground = "#F87070" })
HL("htmlBold", { bold = true })
HL("htmlBoldItalic", { bold = true, italic = true })
HL("htmlBoldItalicUnderline", { bold = true, italic = true, underline = true })
HL("htmlBoldUnderline", { bold = true, underline = true })
HL("htmlBoldUnderlineItalic", { bold = true, italic = true, underline = true })
HL("htmlComment", { foreground = "#515C68" })
HL("htmlCommentError", { foreground = "#F76262" })
HL("htmlCommentNested", { foreground = "#F76262" })
HL("htmlCssDefinition", { foreground = "#FB7373" })
HL("htmlCssStyleComment", { foreground = "#515C68" })
HL("htmlEndTag", { foreground = "#36C692" })
HL("htmlError", { foreground = "#F76262" })
HL("htmlEvent", { foreground = "#FB7373" })
HL("htmlEventDQ", { foreground = "#FB7373" })
HL("htmlEventSQ", { foreground = "#FB7373" })
HL("htmlH1", { bold = true, foreground = "#4B5259" })
HL("htmlH2", { bold = true, foreground = "#4B5259" })
HL("htmlH3", { bold = true, foreground = "#4B5259" })
HL("htmlH4", { bold = true, foreground = "#4B5259" })
HL("htmlH5", { bold = true, foreground = "#4B5259" })
HL("htmlH6", { bold = true, foreground = "#4B5259" })
HL("htmlHead", { foreground = "#F96262" })
HL("htmlItalic", { italic = true })
HL("htmlItalicBold", { bold = true, italic = true })
HL("htmlItalicBoldUnderline", { bold = true, italic = true, underline = true })
HL("htmlItalicUnderline", { italic = true, underline = true })
HL("htmlItalicUnderlineBold", { bold = true, italic = true, underline = true })
HL("htmlLink", { underline = true })
HL("htmlMathTagName", { foreground = "#F87070" })
HL("htmlPreAttr", { foreground = "#79DCAA" })
HL("htmlPreError", { foreground = "#F76262" })
HL("htmlPreProc", { foreground = "#F96262" })
HL("htmlPreProcAttrError", { foreground = "#F76262" })
HL("htmlPreProcAttrName", { foreground = "#F96262" })
HL("htmlPreStmt", { foreground = "#F96262" })
HL("htmlScriptTag", { foreground = "#BE8FD7" })
HL("htmlSpecialChar", { foreground = "#FB7373" })
HL("htmlSpecialTagName", { foreground = "#36C692" })
HL("htmlStatement", { foreground = "#F87070" })
HL("htmlStrike", { strikethrough = true })
HL("htmlString", { foreground = "#79DCAA" })
HL("htmlStyleArg", { foreground = "#79DCAA" })
HL("htmlSvgTagName", { foreground = "#F87070" })
HL("htmlTag", { foreground = "#BE8FD7" })
HL("htmlTagError", { foreground = "#F76262" })
HL("htmlTagName", { foreground = "#F87070" })
HL("htmlTitle", { bold = true, foreground = "#4B5259" })
HL("htmlUnderline", { underline = true })
HL("htmlUnderlineBold", { bold = true, underline = true })
HL("htmlUnderlineBoldItalic", { bold = true, italic = true, underline = true })
HL("htmlUnderlineItalic", { italic = true, underline = true })
HL("htmlUnderlineItalicBold", { bold = true, italic = true, underline = true })
HL("htmlValue", { foreground = "#79DCAA" })
HL("incline__gui_bold", { bold = true })
HL("incline__guibg_171c21__guifg_d4d4d5", { background = "#171C21", foreground = "#D4D4D5" })
HL("incline__guifg_7ab0df", { foreground = "#7AB0DF" })
HL("incline__guifg_c397d8", { foreground = "#C397D8" })
HL("javaScrParenError", { foreground = "#F76262" })
HL("javaScript", { foreground = "#FB7373" })
HL("javaScriptBoolean", { bold = true, foreground = "#F87070" })
HL("javaScriptBraces", { foreground = "#BE8FD7" })
HL("javaScriptBranch", { foreground = "#F87070" })
HL("javaScriptCharacter", { foreground = "#E1C58D" })
HL("javaScriptComment", { foreground = "#515C68" })
HL("javaScriptCommentTodo", { foreground = "#FFE59E" })
HL("javaScriptConditional", { foreground = "#F87070" })
HL("javaScriptConstant", { foreground = "#F87070" })
HL("javaScriptDebug", { foreground = "#FB7373" })
HL("javaScriptDeprecated", { foreground = "#36C692" })
HL("javaScriptEmbed", { foreground = "#FB7373" })
HL("javaScriptError", { foreground = "#F76262" })
HL("javaScriptException", { foreground = "#36C692" })
HL("javaScriptExpression", { foreground = "#FB7373" })
HL("javaScriptFunction", { foreground = "#BE8FD7" })
HL("javaScriptGlobal", { foreground = "#66B3FF" })
HL("javaScriptIdentifier", { foreground = "#36C692" })
HL("javaScriptLabel", { foreground = "#F87070" })
HL("javaScriptLineComment", { foreground = "#515C68" })
HL("javaScriptMember", { foreground = "#66B3FF" })
HL("javaScriptMessage", { foreground = "#66B3FF" })
HL("javaScriptNull", { foreground = "#66B3FF" })
HL("javaScriptOperator", { foreground = "#70C0BA" })
HL("javaScriptRegexpString", { foreground = "#79DCAA" })
HL("javaScriptRepeat", { foreground = "#B77EE0" })
HL("javaScriptReserved", { foreground = "#66B3FF" })
HL("javaScriptSpecial", { foreground = "#FB7373" })
HL("javaScriptSpecialCharacter", { foreground = "#FB7373" })
HL("javaScriptStatement", { foreground = "#F87070" })
HL("javaScriptStringD", { foreground = "#79DCAA" })
HL("javaScriptStringS", { foreground = "#79DCAA" })
HL("javaScriptStringT", { foreground = "#79DCAA" })
HL("javaScriptType", { foreground = "#F87070" })
HL("luaComment", { foreground = "#515C68" })
HL("luaCommentDelimiter", { foreground = "#515C68" })
HL("luaCond", { foreground = "#F87070" })
HL("luaCondElse", { foreground = "#F87070" })
HL("luaConstant", { foreground = "#FF6666" })
HL("luaError", { foreground = "#F76262" })
HL("luaFor", { foreground = "#B77EE0" })
HL("luaFunc", { foreground = "#36C692" })
HL("luaFunction", { foreground = "#BE8FD7" })
HL("luaLabel", { foreground = "#F87070" })
HL("luaMetaMethod", { foreground = "#BE8FD7" })
HL("luaNumber", { foreground = "#54CED6" })
HL("luaOperator", { foreground = "#70C0BA" })
HL("luaParenError", { foreground = "#F76262" })
HL("luaRepeat", { foreground = "#B77EE0" })
HL("luaSpecial", { foreground = "#C397D8" })
HL("luaStatement", { foreground = "#F87070" })
HL("luaString", { foreground = "#79DCAA" })
HL("luaString2", { foreground = "#79DCAA" })
HL("luaStringDelimiter", { foreground = "#79DCAA" })
HL("luaSymbolOperator", { foreground = "#70C0BA" })
HL("luaTable", { foreground = "#5FB0FC" })
HL("luaTodo", { foreground = "#FFE59E" })
HL("markdownAutomaticLink", { foreground = "#F3A4F1" })
HL("markdownBlockquote", { foreground = "#515C68" })
HL("markdownBold", { bold = true })
HL("markdownBoldDelimiter", { bold = true })
HL("markdownBoldItalic", { bold = true, italic = true })
HL("markdownBoldItalicDelimiter", { bold = true, italic = true })
HL("markdownCode", { foreground = "#FB7373" })
HL("markdownCodeDelimiter", { foreground = "#FB7373" })
HL("markdownError", { foreground = "#F76262" })
HL("markdownEscape", { foreground = "#FB7373" })
HL("markdownFootnote", { foreground = "#C397D8" })
HL("markdownFootnoteDefinition", { foreground = "#C397D8" })
HL("markdownH1", { bold = true, foreground = "#4B5259" })
HL("markdownH1Delimiter", { foreground = "#FB7373" })
HL("markdownH2", { bold = true, foreground = "#4B5259" })
HL("markdownH2Delimiter", { foreground = "#FB7373" })
HL("markdownH3", { bold = true, foreground = "#4B5259" })
HL("markdownH3Delimiter", { foreground = "#FB7373" })
HL("markdownH4", { bold = true, foreground = "#4B5259" })
HL("markdownH4Delimiter", { foreground = "#FB7373" })
HL("markdownH5", { bold = true, foreground = "#4B5259" })
HL("markdownH5Delimiter", { foreground = "#FB7373" })
HL("markdownH6", { bold = true, foreground = "#4B5259" })
HL("markdownH6Delimiter", { foreground = "#FB7373" })
HL("markdownHeadingDelimiter", { foreground = "#FB7373" })
HL("markdownHeadingRule", { foreground = "#F96262" })
HL("markdownId", { foreground = "#F87070" })
HL("markdownIdDeclaration", { foreground = "#C397D8" })
HL("markdownItalic", { italic = true })
HL("markdownItalicDelimiter", { italic = true })
HL("markdownLinkText", { underline = true })
HL("markdownListMarker", { foreground = "#F87070" })
HL("markdownOrderedListMarker", { foreground = "#F87070" })
HL("markdownRule", { foreground = "#F96262" })
HL("markdownUrl", { foreground = "#F3A4F1" })
HL("markdownUrlDelimiter", { foreground = "#BE8FD7" })
HL("markdownUrlTitle", { foreground = "#79DCAA" })
HL("markdownUrlTitleDelimiter", { foreground = "#FB7373" })
HL("mkdEscape", { foreground = "#FB7373" })
HL("monarkNormal", { foreground = "#79DCAA" })
HL("rainbowcol1", { foreground = "#D098FF" })
HL("rainbowcol2", { foreground = "#79CAFF" })
HL("rainbowcol3", { foreground = "#94CAF9" })
HL("rainbowcol4", { foreground = "#50E0AC" })
HL("rainbowcol5", { foreground = "#FFE981" })
HL("rainbowcol6", { foreground = "#FF9393" })
HL("rainbowcol7", { foreground = "#FF8D8D" })
HL("vbBoolean", { bold = true, foreground = "#F87070" })
HL("vbComment", { foreground = "#515C68" })
HL("vbConditional", { foreground = "#F87070" })
HL("vbConst", { foreground = "#FF6666" })
HL("vbDefine", { foreground = "#FF6666" })
HL("vbError", { foreground = "#F76262" })
HL("vbEvents", { foreground = "#FB7373" })
HL("vbFloat", { foreground = "#F3A4F1" })
HL("vbFunction", { foreground = "#36C692" })
HL("vbIdentifier", { foreground = "#36C692" })
HL("vbKeyword", { foreground = "#F87070" })
HL("vbLineLabel", { foreground = "#515C68" })
HL("vbLineNumber", { foreground = "#515C68" })
HL("vbMethods", { foreground = "#F96262" })
HL("vbNumber", { foreground = "#54CED6" })
HL("vbOperator", { foreground = "#70C0BA" })
HL("vbPreProc", { foreground = "#F96262" })
HL("vbRepeat", { foreground = "#B77EE0" })
HL("vbStatement", { foreground = "#F87070" })
HL("vbString", { foreground = "#79DCAA" })
HL("vbTodo", { foreground = "#FFE59E" })
HL("vbTypeSpecifier", { foreground = "#F87070" })
HL("vbTypes", { foreground = "#F87070" })
HL("xmlAttrib", { foreground = "#F87070" })
HL("xmlAttribPunct", { foreground = "#515C68" })
HL("xmlCdata", { foreground = "#79DCAA" })
HL("xmlCdataCdata", { foreground = "#F87070" })
HL("xmlCdataEnd", { foreground = "#F87070" })
HL("xmlCdataStart", { foreground = "#F87070" })
HL("xmlComment", { foreground = "#515C68" })
HL("xmlCommentError", { foreground = "#F76262" })
HL("xmlCommentPart", { foreground = "#515C68" })
HL("xmlCommentStart", { foreground = "#515C68" })
HL("xmlDocTypeDecl", { foreground = "#BE8FD7" })
HL("xmlDocTypeKeyword", { foreground = "#F87070" })
HL("xmlEndTag", { foreground = "#36C692" })
HL("xmlEntity", { foreground = "#F87070" })
HL("xmlEntityPunct", { foreground = "#F87070" })
HL("xmlError", { foreground = "#F76262" })
HL("xmlInlineDTD", { foreground = "#BE8FD7" })
HL("xmlNamespace", { foreground = "#7AB0DF" })
HL("xmlProcessing", { foreground = "#F87070" })
HL("xmlProcessingDelim", { foreground = "#515C68" })
HL("xmlString", { foreground = "#79DCAA" })
HL("xmlTag", { foreground = "#BE8FD7" })
HL("xmlTagName", { foreground = "#BE8FD7" })
HL("xmlTodo", { foreground = "#FFE59E" })

---vim:filetype=lua
