return {
  setup = function(colors)
    hi("CmpItemKindText", { guifg = colors.syntax.color16, guibg = colors.kinds.Text })
    hi("CmpItemKindMethod", { guifg = colors.syntax.color00, guibg = colors.kinds.Method })
    hi("CmpItemKindSnippet", { guifg = colors.syntax.color03, guibg = colors.kinds.Snippet })
    hi("CmpItemKindFunction", { guifg = colors.syntax.color01, guibg = colors.kinds.Function })
    hi("CmpItemKindConstructor", { guifg = colors.syntax.color06, guibg = colors.kinds.Constructor })
    hi("CmpItemKindField", { guifg = colors.syntax.color04, guibg = colors.kinds.Field })
    hi("CmpItemKindVariable", { guifg = colors.syntax.color02, guibg = colors.kinds.Variable })
    hi("CmpItemKindClass", { guifg = colors.syntax.color01, guibg = colors.kinds.Class })
    hi("CmpItemKindInterface", { guifg = colors.syntax.color13, guibg = colors.kinds.Interface })
    hi("CmpItemKindModule", { guifg = colors.syntax.color13, guibg = colors.kinds.Module })
    hi("CmpItemKindProperty", { guifg = colors.syntax.color20, guibg = colors.kinds.Property })
    hi("CmpItemKindUnit", { guifg = colors.syntax.color19, guibg = colors.kinds.Unit })
    hi("CmpItemKindValue", { guifg = colors.syntax.color08, guibg = colors.kinds.Value })
    hi("CmpItemKindEnum", { guifg = colors.syntax.color06, guibg = colors.kinds.Enum })
    hi("CmpItemKindKeyword", { guifg = colors.syntax.color15, guibg = colors.kinds.Keyword })
    hi("CmpItemKindColor", { guifg = colors.syntax.color17, guibg = colors.kinds.Color })
    hi("CmpItemKindFile", { guifg = colors.syntax.color10, guibg = colors.kinds.File })
    hi("CmpItemKindReference", { guifg = colors.syntax.color10, guibg = colors.kinds.Reference })
    hi("CmpItemKindFolder", { guifg = colors.syntax.color17, guibg = colors.kinds.Folder })
    hi("CmpItemKindEnumMember", { guifg = colors.syntax.color20, guibg = colors.kinds.EnumMember })
    hi("CmpItemKindConstant", { guifg = colors.syntax.color19, guibg = colors.kinds.Constant })
    hi("CmpItemKindStruct", { guifg = colors.syntax.color00, guibg = colors.kinds.Struct })
    hi("CmpItemKindEvent", { guifg = colors.syntax.color00, guibg = colors.kinds.Event })
    hi("CmpItemKindOperator", { guifg = colors.syntax.color0, guibg = colors.kinds.Operator })
    hi("CmpItemKindTypeParameter", { guifg = colors.syntax.color05, guibg = colors.kinds.TypeParameter })
    hi("CmpItemMenu", { guifg = colors.syntax.color10 })
    hi("CmpItemAbbr", { guifg = colors.syntax.color15 })
    hi("CmpItemAbbrMatchFuzzy", { guifg = colors.syntax.color00 })
    hi("CmpItemAbbrMatch", { guifg = colors.syntax.color06 })
    hi("CmpItemAbbrMatchDeprecated", { guifg = colors.syntax.color08 })
  end,
}

-- vim:ft=lua
