local M = {}

M.plug = {
  "hinell/move.nvim",
  "MattesGroeger/vim-bookmarks",
  "rcarriga/nvim-notify",
  "kshenoy/vim-signature",
  "mbbill/undotree",
  "b0o/schemastore.nvim",
  "kosayoda/nvim-lightbulb",
  "rafcamlet/nvim-luapad",
  "stevearc/aerial.nvim",
  "tpope/vim-repeat",
  "ggandor/flit.nvim",
  "cbochs/grapple.nvim",
  "cbochs/portal.nvim",
  "stevearc/overseer.nvim",
  "ThePrimeagen/harpoon",
  "elkowar/yuck.vim",
  "hrsh7th/cmp-nvim-lua",
  "hrsh7th/cmp-nvim-lsp-signature-help",
  "hrsh7th/cmp-nvim-lsp-document-symbol",
  "hrsh7th/cmp-cmdline",
  "tami5/sqlite.lua",
  "simrat39/rust-tools.nvim",
  "mfussenegger/nvim-jdtls",
  "simrat39/symbols-outline.nvim",
  "j-hui/fidget.nvim",
  "wakatime/vim-wakatime",
  "karb94/neoscroll.nvim",
  "andweeb/presence.nvim",
  "nvim-telescope/telescope-dap.nvim",
  "tom-anders/telescope-vim-bookmarks.nvim",
  "nvim-treesitter/nvim-tree-docs",
  "p00f/nvim-ts-rainbow",
  "nvim-treesitter/nvim-treesitter-textobjects",
  "windwp/nvim-ts-autotag",
  "goolord/alpha-nvim",
  "b0o/incline.nvim",
  "lukas-reineke/virt-column.nvim",
  "petertriho/nvim-scrollbar",
  "folke/twilight.nvim",
  "Pocco81/TrueZen.nvim",
  "yamatsum/nvim-cursorline",
  "anuvyklack/pretty-fold.nvim",
  "echasnovski/mini.indentscope",
  "gorbit99/codewindow.nvim",
  "stevearc/resession.nvim",
  "ThePrimeagen/refactoring.nvim",
  "is0n/jaq-nvim",
  "sindrets/diffview.nvim",
  "kevinhwang91/nvim-hlslens",
  "dnlhc/glance.nvim",
  "Fymyte/rasi.vim",
  "kovetskiy/sxhkd-vim",
  "MTDL9/vim-log-highlighting",
  "TimUntersberger/neogit",
  "lewis6991/gitsigns.nvim",
  "folke/trouble.nvim",
  "NFrid/due.nvim",
  "phelipetls/vim-hugo",
  "robertbasic/vim-hugo-helper",
  "kyazdani42/nvim-tree.lua",
}

M.spec = {}

return M

-- vim:filetype=lua
