local M = {
  border = "solid",
  cmp_border = "none",
  gitsigns = {
    topdelete = " ",
    changedelete = "▌",
    delete = " ",
    change = "▌",
    add = "▌",
  },
  scrollbar = {
    Search = { "-", "=" },
    Error = { "-", "=" },
    Warn = { "-", "=" },
    Info = { "-", "=" },
    Hint = { "-", "=" },
    Misc = { "-", "=" },
    GitAdd = "▁",
    GitChange = "▁",
    GitDelete = "▁",
  },
  neogit = {
    section = { "", "" },
    item = { "", "" },
    hunk = { "", "" },
  },
  fold = {
    number_of_folded_line = " ",
    percentage = ": ",
    padding = " ",
    fill_char = "•",
  },
  todo = {
    FIX = " ",
    BUG = " ",
    TODO = " ",
    WANTS = " ",
    HACK = " ",
    CHORE = " ",
    CLEAN = " ",
    WARN = " ",
    PERF = " ",
    NOTE = " ",
    UPDATE = " ",
    DEMO = " ",
    IMPROVE = " ",
    TEST = "ﭧ",
  },
  monark = {
    normal = " ",
    visual = " ",
    line = " ",
    block = " ",
    select = " ",
    insert = " ",
    replace = " ",
    terminal = " ",
  },
  undo = {
    TreeNodeShape = "*",
    TreeVertShape = "|",
    TreeSplitShape = "/",
    TreeReturnShape = "\\",
  },
  notify = {
    ERROR = "",
    WARN = "",
    INFO = "",
    DEBUG = "",
    TRACE = "",
  },
  tree = {
    diagnostic = {
      hint = "",
      info = "",
      warning = "",
      error = "",
    },
    symlink = "→ ",
    line = {
      corner = "└",
      edge = "│",
      item = "│",
      bottom = "─",
      none = " ",
    },
    glyphs = {
      default = "",
      symlink = "",
      bookmark = "",
      git = {
        deleted = "",
        ignored = "",
        renamed = "",
        staged = "",
        unmerged = "",
        unstaged = "",
        untracked = "",
      },
      folder = {
        default = "",
        arrow_open = "",
        arrow_closed = "",
        empty = "",
        empty_open = "",
        open = "",
        symlink = "",
        symlink_open = "",
      },
    },
  },
  glance = {
    top_char = " ",
    bottom_char = " ",
    indent = "┃",
  },
  sign = {
    diagnostic = "",
    errors = "",
    hints = "",
    warning = "",
    info = "",
    bulb = "",
    breakpoint = "",
    logpoint = "",
    condition = "",
    rejected = "",
    stopped = "",
  },
  dap = {
    main = { expanded = "", collapsed = "", current_frame = "" },
    controls = {
      pause = "",
      play = "",
      step_into = "",
      step_over = "",
      step_out = "",
      step_back = "",
      run_last = "",
      terminate = "",
    },
  },
  mason = {
    package_installed = " ",
    package_pending = " ",
    package_uninstalled = "◍ ",
  },
  bookmark = {
    annotation = "",
    sign = "♥",
  },
  blankline = {
    char = "│",
    context_char_list = { "┃" },
    space_char_blankline = " ",
  },
  lazy = {
    cmd = " ",
    config = "",
    event = "",
    ft = " ",
    init = " ",
    import = " ",
    keys = " ",
    lazy = "鈴 ",
    loaded = "●",
    not_loaded = "○",
    plugin = " ",
    runtime = " ",
    source = " ",
    start = "",
    task = "✔ ",
    list = {
      "●",
      "➜",
      "★",
      "‒",
    },
  },
  trouble = {
    fold_opened = "",
    fold_closed = "",
    sign = {
      error = "",
      warning = "",
      hint = "",
      information = "",
      other = "﫠",
    },
  },
  small = {
    virtualcolumn = "┃",
    scope = "┃",
  },
  navic = {
    separator = "  ",
    depth = "… ",
  },
  aerial = {
    mid_item = "├─",
    last_item = "└─",
    nested_top = "│ ",
    whitespace = "  ",
  },
}

return M

-- vim:filetype=lua
