-- TODO: Use plenary.scandir.scan_dir for this.
return {
  ["bashls"] = {},
  ["jdtls"] = require("plugin.config.lsp.servers.jdtls"),
  ["jsonls"] = require("plugin.config.lsp.servers.jsonls"),
  ["yamlls"] = {},
  ["pyright"] = {},
  ["sumneko_lua"] = require("plugin.config.lsp.servers.sumneko_lua"),
  ["cssls"] = {},
  ["texlab"] = require("plugin.config.lsp.servers.texlab"),
  ["ltex"] = {},
  ["stylelint_lsp"] = {},
  ["emmet_ls"] = require("plugin.config.lsp.servers.emmet_ls"),
  ["tailwindcss"] = {},
  ["grammarly"] = {},
  ["html"] = {},
  ["reason_ls"] = {},
  ["awk_ls"] = {},
  ["vimls"] = {},
  ["clangd"] = require("plugin.config.lsp.servers.clangd"),
  ["rust_analyzer"] = {},
  ["sourcery"] = require("plugin.config.lsp.servers.sourcery"),
}
