local M = {}

M.options = {
  ["normal"] = {
    ["termguicolors"] = true,
    ["laststatus"] = 2,
    ["completeopt"] = "menuone,noselect",
    ["shadafile"] = "",
    ["title"] = true,
    ["hidden"] = true,
    ["signcolumn"] = "yes",
    ["splitbelow"] = true,
    ["splitright"] = true,
    ["clipboard"] = "unnamedplus",
    ["cmdheight"] = 1,
    ["expandtab"] = true,
    ["shiftwidth"] = 2,
    ["softtabstop"] = 2,
    ["wildignore"] = { "*/cache/*", "*/tmp/*" },
    ["smartindent"] = true,
    ["fillchars"] = {
      ["eob"] = " ",
      ["vert"] = "▎",
      ["stlnc"] = "━",
      ["diff"] = "░",
      ["msgsep"] = "━",
      ["foldopen"] = "▾",
      ["foldsep"] = "|",
      ["foldclose"] = "▸",
    },
    ["ignorecase"] = false,
    ["smartcase"] = true,
    ["mouse"] = "a",
    ["undolevels"] = 1000,
    ["number"] = true,
    ["numberwidth"] = 2,
    ["relativenumber"] = false,
    ["fileencoding"] = "utf-8",
    ["tabstop"] = 2,
    ["timeoutlen"] = 250,
    ["undofile"] = true,
    ["updatetime"] = 250,
    ["wrap"] = true,
    ["list"] = true,
    ["spell"] = false,
    ["spelllang"] = "en_us,en_gb,cjk",
    ["spellsuggest"] = "best,9",
    ["scrolloff"] = 8,
    ["sidescrolloff"] = 8,
    ["backup"] = false,
    ["showmode"] = true,
    ["showcmd"] = true,
    ["hlsearch"] = true,
    ["conceallevel"] = 2,
    ["swapfile"] = false,
    ["cursorline"] = true,
    ["autowrite"] = true,
    ["autoindent"] = true,
    ["cursorlineopt"] = "both",
    ["signcolumn"] = "yes",
    ["pumheight"] = 30,
    ["pumwidth"] = 35,
    ["pumblend"] = 0,
    ["history"] = 1000,
    ["emoji"] = true,
    ["ruler"] = false,
    ["list"] = true,
    ["menuitems"] = 30,
    ["magic"] = true,
    ["icon"] = true,
  },
  ["append"] = {
    ["whichwrap"] = "<>[]hl",
    ["errorformat"] = "%f|%l col %c|%m",
    ["shortmess"] = "sI",
  },
}

M.autocmds = {
  ["relative_feedback"] = false,
  ["number_feedback"] = false,
  ["listchars_feedback"] = false,
  ["cursorline_feedback"] = false,
  ["yank_feedback"] = false,
  ["scrollbar_init"] = false,
  ["term_non_relative"] = true,
  ["filetype_format"] = true,
  ["block_read_only"] = true,
  ["plugins_auto_source"] = false,
  ["nvimrc_auto_source"] = false,
}

M.theme = { ["colorscheme"] = "everforest", ["background"] = "dark" }

M.globals = {
  ["mapleader"] = " ",
  ["did_load_filetypes"] = 1,
  ["zoom#statustext"] = "Z",
  ["markdown_fenced_languages"] = {
    "lua",
    "vim",
    "json",
    "typescript",
    "javascript",
    "js=javascript",
    "ts=typescript",
    "shell=sh",
    "python",
    "sh",
    "console=sh",
  },
  ["python3_host_prog"] = "python3",
}

M.miscmds = {
  ["ease_quit"] = false,
}

local file_name = "_compiled"
M.compiled = {
  ["file_name"] = file_name,
  ["full_path"] = vim.fn.stdpath "config" .. "/lua/configs/core/" .. file_name .. ".lua",
  ["impatient"] = "configs.core." .. file_name,
}

M.builtins = {
  ["2html_plugin"] = true,
  ["getscript"] = true,
  ["getscriptPlugin"] = true,
  ["gzip"] = true,
  ["logipat"] = true,
  ["netrw"] = true,
  ["netrwPlugin"] = true,
  ["netrwSettings"] = true,
  ["netrwFileHandlers"] = true,
  ["matchit"] = true,
  ["tar"] = true,
  ["tarPlugin"] = true,
  ["rrhelper"] = true,
  ["vimball"] = true,
  ["vimballPlugin"] = true,
  ["zip"] = true,
  ["zipPlugin"] = true,
  ["tutor_mode_plugin"] = true,
  ["filetype"] = true,
  ["ftoff"] = true,
  ["ftplugin"] = true,
  ["ftplugof"] = true,
  ["fzf"] = true,
  ["spellfile_plugin"] = true,
}

M.plugins = {
  ["completion"] = {
    ["nvim-cmp"] = true,
    ["cmp-under-comparator"] = true,
    ["cmp-zsh"] = true,
    ["cmp-dictionary"] = true,
    ["LuaSnip"] = true,
    ["nvim-autopairs"] = true,
    ["cmp-git"] = true,
    ["cmp-emoji"] = true,
    ["cmp-look"] = true,
    ["cmp-calc"] = true,
    ["cmp-spell"] = true,
    ["cmp-omni"] = true,
    ["cmp-rg"] = true,
    ["cmp-treesitter"] = true,
    ["cmp-nvim-lsp-document-symbol"] = true,
    ["cmp-nvim-lsp-signature-help"] = true,
    ["cmp-nvim-lua"] = true,
    ["cmp-cmdline-history"] = true,
    ["cmp-fish"] = true,
    ["cmp-nvim-tags"] = true,
    ["cmp-npm"] = true,
    ["cmp-tmux"] = true,
    ["cmp-latex-symbols"] = true,
    ["cmp_luasnip"] = true,
    ["cmp-cmdline"] = true,
    ["cmp-nvim-lsp"] = true,
    ["cmp-buffer"] = true,
    ["cmp-path"] = true,
  },
  ["core"] = {
    ["packer.nvim"] = true,
    ["impatient.nvim"] = true,
  },
  ["editing"] = {
    ["rasi.vim"] = false,
    ["yuck.vim"] = false,
    ["sxhkd-vim"] = false,
    ["vim-log-highlighting"] = false,
    ["vim-polyglot"] = false,
    ["neogit"] = false,
    ["todo-comments.nvim"] = false,
    ["trouble.nvim"] = false,
    ["markdown-preview.nvim"] = false,
    ["gitsigns.nvim"] = true,
    ["Comment.nvim"] = true,
    ["nvim-colorizer.lua"] = true,
  },
  ["utils"] = {
    ["nvim-notify"] = false,
    ["plenary.nvim"] = true,
    ["popup.nvim"] = true,
    ["filetype.nvim"] = true,
    ["stabilize.nvim"] = true,
  },
  ["workflow"] = {
    ["nvim-neoclip.lua"] = false,
    ["telescope-dict.nvim"] = false,
    ["telescope-command-palette.nvim"] = false,
    ["telescope-node-modules.nvim"] = false,
    ["telescope-luasnip.nvim"] = false,
    ["telescope-emoji.nvim"] = false,
    ["telescope-heading.nvim"] = false,
    ["telescope-bookmarks.nvim"] = false,
    ["telescope-frecency.nvim"] = false,
    ["telescope-tele-tabby.nvim"] = false,
    ["telescope-repo.nvim"] = false,
    ["telescope-media-files.nvim"] = false,
    ["telescope-project.nvim"] = false,
    ["telescope-packer.nvim"] = false,
    ["telescope-file-browser.nvim"] = false,
    ["telescope-env.nvim"] = true,
    ["cheatsheet.nvim"] = true,
    ["telescope-fzf-native.nvim"] = true,
    ["telescope-symbols.nvim"] = true,
    ["telescope.nvim"] = true,
    ["nvim-tree.lua"] = true,
  },
  ["ui"] = {},
  ["others"] = {},
  ["development"] = {},
}

M.modules = {
  ["ui"] = { enabled = true, import = "plugins.ui" },
  ["others"] = { enabled = true, import = "plugins.others" },
  ["development"] = { enabled = true, import = "plugins.development" },
  ["workflow"] = { enabled = true, import = "plugins.workflow" },
  ["utils"] = { enabled = true, import = "plugins.utils" },
  ["editing"] = { enabled = true, import = "plugins.editing" },
  ["core"] = { enabled = true, import = "plugins.core" },
  ["completion"] = { enabled = true, import = "plugins.completion" },
}

M.kinds = {
  source = {
    nvim_lua = " LUA",
    nvim_lsp = " LSP",
    tags = " TAG",
    zsh = " ZSH",
    fish = " FIS",
    buffer = " BUF",
    path = " PTH",
    spell = " SPL",
    dictionary = " DIC",
    luasnip = " LSN",
    nvim_lsp_signature_help = " SGH",
    orgmode = " ORG",
    treesitter = " TSR",
    rg = " RIP",
    omni = " OMN",
    look = " LOK",
    calc = " CAL",
    emoji = " EMJ",
    tmux = " TMX",
    npm = " NPM",
    cmp_git = " GIT",
    latex_symbols = " TEX",
    nvim_lsp_document_symbol = " DSM",
    buffer = " BUF",
    cmdline = "גּ CML",
    cmdline_history = " CMH",
  },
  item = {
    Text = "",
    Method = "",
    Function = "",
    Constructor = "",
    Field = "ﰠ",
    Variable = "",
    Class = "ﴯ",
    Interface = "",
    Module = "",
    Property = "ﰠ",
    Unit = "塞",
    Value = "",
    Enum = "",
    Keyword = "",
    Snippet = "",
    Color = "",
    File = "",
    Reference = "",
    Folder = "",
    EnumMember = "",
    Constant = "",
    Struct = "פּ",
    Event = "",
    Operator = "",
    TypeParameter = "",
  },
}

return M
